### ISSUE TITLE
Browser detection do not switch

### ISSUE THREAD

**Issue by KStenK** [nuxt-modules/i18n#1157] opened 2021-04-24 19:21 UTC
Hi there,

I am trying to configure the nuxt-i18n plugin, but I can't get it to work like I like to.
I have followed the documentation for a pretty long time and I'm not sure, is it a bug or I'm doing something wrong or I have misunderstood something.
I am still testing everything in the development environment.

Configuration:
```
  i18n: {
    locales: [
      {code: 'et', iso: 'et', file: 'et.json', flag: '/images/et-flag.svg'},
      {code: 'en', iso: 'en', file: 'en.json', flag: '/images/en-flag.svg'},
      {code: 'ru', iso: 'ru', file: 'ru.json', flag: '/images/ru-flag.svg'},
    ],
    langDir: '~/locales/',
    defaultLocale: 'ru',
    lazy: true,
    strategy: 'no_prefix',
    detectBrowserLanguage: {
      alwaysRedirect: true,
      useCookie: true,
      cookieKey: 't_locale',
      fallbackLocale: 'et'
    }
  }
```

Browser settings:

- From console `navigator.language` outputs: `"en-US"`.
- Accept language in request header: `Accept-Language: en-US,en;q=0.9`.

Now if I go to the `/` path without any cookies set, I see the `defaultLocale` language.

No switching is done to the 'en' (browser) locale. As I understand that after browser detection I should be switched to the browser preferred locale. From the cookie, I see that value is set to 'ru', which is strange.

When i set `detectBrowserLanguage.useCookie: false`, and delete the cookie and refresh the page, I see first `defaultLocale` language and then switching to 'en' language, which looks correct for me.

If `useCookie` is set to `true`, it looks like it will set the cookie on the `defaultLocale`, before the browser can detect language.

In the documentation behind the `cookieKey` option there is the description: `If enabled, a cookie is set once the user has been redirected to browser's preferred locale, to prevent subsequent redirections. `.

I don't know now, even to the `fallbackLocale` there is no switching.

Any idea what I'm doing wrong?

Dependencies:
```
"nuxt": "^2.15.3"
"nuxt-i18n": "^6.26.0"
```

**Comment by rchl** [comment] 2021-04-24 21:11
I can't reproduce. It detects locale as `en` for me with a config like that.

Can you reproduce on this project that is based on your configuration? https://codesandbox.io/s/nuxt-nuxt-i18n-base-template-sty4f?file=/nuxt.config.js

**Comment by KStenK** [comment] 2021-04-24 21:58
I think I found the problem.

In the `nuxt.config.js` I had `target` setting  `static`.
If I set it to `server` it started working correctly.
Should it be like this?

Reproduced it here: https://codesandbox.io/s/nuxt-nuxt-i18n-base-template-forked-kegmi

**Comment by rchl** [comment] 2021-04-25 20:54
I'm not sure what to think of it.

It seems like `nuxt dev` and `target: 'static'` is a weird combination that isn't really equivalent to a real-world situation where `target: 'static'` is used with `nuxt generate` and deployed to a static hosting.

With `nuxt dev` the site served by Nuxt seems to be pre-generated (like it would be with `nuxt generate`) but Nuxt also allows the `Set-cookie` header to be sent with the response which would not happen in a real-world scenario using static hosting.

CC @pi0 @danielroe Any opinions?
(Note that I haven't investigated this issue thoroughly but the fact that `Set-cookie` header is received with the response doesn't seem appropriate if `nuxt dev` with `target: 'static'` is supposed to emulate real static hosting).

**Comment by rchl** [comment] 2021-06-26 09:50
I guess that it might be fixable in the module if we avoid setting the cookie when in `process.static`.

**Comment by MechaGirls** [comment] 2021-11-04 03:57
> 我想我发现了问题。
> 
> 在`nuxt.config.js`I had`target`设置中 `static`。 如果我将它设置为`server`它开始正常工作。 应该是这样吗？
> 
> 转载在这里：[https](https://codesandbox.io/s/nuxt-nuxt-i18n-base-template-forked-kegmi) : [//codesandbox.io/s/nuxt-nuxt-i18n-base-template-forked-kegmi](https://codesandbox.io/s/nuxt-nuxt-i18n-base-template-forked-kegmi)

That happened to me, too

**Comment by janwendt** [comment] 2021-12-13 21:18
I have the same problem in dev. It works in production (after nuxt generate).

**Comment by BobbieGoede** [comment] 2024-09-21 20:23
Closing this as v7 is not being actively worked on (critical hotfixes only), if this still applies to v8 and later please open a new issue!

**Closed as not planned by BobbieGoede** 2024-09-21 20:23 UTC
Labels: pinned 📌, scope: ssg, v7
