### ISSUE TITLE
Crashes using Nuxt3.0.0 

### ISSUE THREAD

**Issue by ahoiroman** [nuxt-modules/i18n#1652] opened 2022-11-16 15:38 UTC
### Version
@nuxtjs/i18n: 8.0.0-beta.4
nuxt: 3.0.0

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [ ] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [x] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration

```
- Operating System: `Darwin`
- Node Version:     `v18.11.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `build`, `modules`, `publicRuntimeConfig`, `privateRuntimeConfig`, `globalName`, `app`, `i18n`, `http`, `proxy`, `auth`, `tailwindcss`, `googleFonts`
- Runtime Modules:  `@nuxtjs-alt/auth@2.0.16`, `@nuxtjs-alt/http@1.4.6`, `@nuxtjs-alt/proxy@1.3.8`, `@nuxt/content@2.2.2`, `@nuxtjs/tailwindcss@6.1.3`, `@nuxtjs/google-fonts@3.0.0-1`, `@pinia/nuxt@0.4.3`, `@nuxtjs/i18n@8.0.0-beta.4`, `@nuxt/image-edge@1.0.0-27809804.194d2d6`
- Build Modules:    `-`
```

```
    i18n: {
        locales: [
            {
                code: 'en',
                file: 'en-GB.json'
            },
            {
                code: 'de',
                file: 'de-DE.json'
            }
        ],
        strategy: 'prefix_and_default',
        detectBrowserLanguage: {
            useCookie: true,
            cookieKey: 'lang',
            redirectOn: 'root',  // recommended
        },
        langDir: 'locales/',
        defaultLocale: 'de',
        lazy: true
    },
```

### Steps to reproduce

Run `npm run dev`

### What is Expected?

Nutt running

### What is actually happening?

```
 ERROR  Cannot start nuxt:  Cannot find module '@intlify/vue-i18n-bridge/lib/index.mjs'
Require stack:
- /Users/ahoi/Entwicklung/nuxtjs/web/index.js
```

**Comment by MusicOnline** [comment] 2022-11-16 15:53
Duplicate of #1640

**Closed as not planned** 2022-11-17 08:46 UTC
Labels: bug 🐛

**Comment by agracia-foticos** [comment] 2022-11-17 13:56
Same issue
