### ISSUE TITLE
[next] Docs contain hydration mismatch

### ISSUE THREAD

**Issue by TheAlexLichter** [nuxt-modules/i18n#1641] opened 2022-11-13 12:50 UTC
### Version

Doesn't matter

### Reproduction Link

https://v8.i18n.nuxtjs.org/getting-started/setup/

### Steps to reproduce

1. Go to that site
2. See that navbar is gone and the console has an error

### What is Expected?

No error & sidebar

**Comment by rchl** [comment] 2022-11-13 14:33
Duplicate of #1631

**Closed as not planned by rchl** 2022-11-13 14:33 UTC
Labels: bug 🐛
