### ISSUE TITLE
`useLocalePath` return an empty string for already localized path

### ISSUE THREAD

**Issue by lukasaric** [nuxt-modules/i18n#2384] opened 2023-09-07 10:35 UTC
### Environment

Local environment

### Reproduction

Try to pass already localized path to the `useLocalePath` and it will return an empty string.

```ts
const localePath = useLocalePath()
const localizedPath = localePath('/en/homepage')
const repeatedLocalizedPath = localePath(localizedPath)
// repeatedLocalizedPath will be: `' '`
```

### Describe the bug

Try to pass already localized path to the `useLocalePath` and it will return an empty string.
The expected behavior is to return the `already localized path that is sent`.

**Comment by BobbieGoede** [comment] 2023-09-07 10:45
Paths should start with a `/`, so `en/homepage` is not a valid (localized) path, try passing `/en/homepage`. 

When passing strings that do not start with a `/` such as `en/homepage`, `localePath` will try to find a route with the name `en/homepage`. 

Passing path:
```ts
const localizedPath = localePath('/en/homepage')
const repeatedLocalizedPath = localePath(localizedPath)
// repeatedLocalizedPath will be: `'/en/homepage'`
```

Passing name:
```ts
const localizedPath = localePath('homepage', 'en')
const repeatedLocalizedPath = localePath(localizedPath, 'en')
// repeatedLocalizedPath will (likely) be: `'/en/homepage'`
```

Please let me know if you have any more questions! I'll close this as it is expected behaviour.

**Closed as completed by BobbieGoede** 2023-09-07 10:45 UTC
Labels: pending triage

**Comment by lukasaric** [comment] 2023-09-07 10:52
> Paths should start with a `/`, so `en/homepage` is not a valid (localized) path, try passing `/en/homepage`.
> 
> When passing strings that do not start with a `/` such as `en/homepage`, `localePath` will try to find a route with the name `en/homepage`.
> 
> Passing path:
> 
> ```ts
> const localizedPath = localePath('/en/homepage')
> const repeatedLocalizedPath = localePath(localizedPath)
> // repeatedLocalizedPath will be: `'/en/homepage'`
> ```
> 
> Passing name:
> 
> ```ts
> const localizedPath = localePath('homepage', 'en')
> const repeatedLocalizedPath = localePath(localizedPath, 'en')
> // repeatedLocalizedPath will (likely) be: `'/en/homepage'`
> ```
> 
> Please let me know if you have any more questions! I'll close this as it is expected behaviour.

@BobbieGoede  I wrote a wrong description (I tried it with the `/` at the frist place and it still return an empty string)

**Comment by BobbieGoede** [comment] 2023-09-07 10:56
I'm unable to reproduce this behaviour, can you provide a minimal reproduction project? You can use [this starter](https://stackblitz.com/fork/github/BobbieGoede/nuxt-i18n-starter/tree/v8) if that helps.

**Comment by lukasaric** [comment] 2023-09-07 10:58
> I'm unable to reproduce this behaviour, can you provide a minimal reproduction project? You can use [this starter](https://stackblitz.com/fork/github/BobbieGoede/nuxt-i18n-starter/tree/v8) if that helps.

@BobbieGoede Oh I figure it out. Somebody used `router.resolve` before sending it to the locale path.
Nvm it should work than if I remove it
