### ISSUE TITLE
How can I translate url using differentDomain=true?

### ISSUE THREAD

**Issue by enriqueaparicio-ph** [nuxt-modules/i18n#980] opened 2020-12-03 19:31 UTC
Hi there,

I am using the module with differentDomain=true, but I do not understand how can I do the routing.

I want to solve this problem:

- mydomain.es/sobre-nosotros -> pointing to about.vue
- mydomain.es/equipo -> pointing to about.vue

and
- mydomain.com/about-us -> pointing to about.vue

Thank you in advance

using last version of nuxt and i18n-module

**Comment by rchl** [comment] 2020-12-03 20:41
So you want to have two different paths for the same page, for Spanish locale?

I don't think that's doable regardless if using `differentDomains` or not...

**Comment by enriqueaparicio-ph** [comment] 2020-12-09 08:13
I want to have two different paths for the same page (for Spanish locale) and be able to manage translations for my urls. 
Thanks @rchl

**Comment by rchl** [comment] 2020-12-09 08:20
I don't think it's a good idea though because a duplicated page like that would cause SEO issues. I would suggest that you use [extendRoutes](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-router#extendroutes) instead and add a [redirect route](https://router.vuejs.org/guide/essentials/redirect-and-alias.html).

**Comment by enriqueaparicio-ph** [comment] 2020-12-09 08:33
Thanks, and How can I handle the translations? using differentDomains I have different urls for the same component (or path in nuxt):

mydomain.es/sobre-nosotros -> pointing to about.vue
mydomain.com/about-us -> pointing to about.vue

**Comment by rchl** [comment] 2020-12-09 08:48
https://i18n.nuxtjs.org/routing#custom-paths

**Comment by enriqueaparicio-ph** [comment] 2020-12-09 09:07
Thanks for the link, but tell me if I am wrong, I am using differentDomain = true, and the strategy set to "no-prefix", the problem is with that strategy doesn't support Custom paths :S

**Comment by rchl** [comment] 2020-12-09 09:11
Just don't set `strategy` when using `differentDomains`. It has some special handing for prefixes. I guess that should be mentioned in the docs.

**Comment by enriqueaparicio-ph** [comment] 2020-12-09 11:15
I couldn't find it in the docs.

I have tried with no strategy, but the routing is not working as expected.

I have this config:
```
   locales: [
      {
        code: 'en',
        iso: 'en-GB',
        domain: 'mydomain.com' 
      },
      {
        code: 'es',
        iso: 'es-ES',
        domain: 'mydomain.es'
      }
    ],
    differentDomains: true, 
    lazy: true,
    defaultLocale: 'es',
    detectBrowserLanguage: false,
    langDir: 'lang/',
    parsePages: false,
    pages: {
      'test/_slug/index': {
        en: '/about-us/:slug',
        es: '/sobre-nosotros/:slug'
      }
    },
    encodePaths: false,
    seo: false
```

If I try: 

- mydomain.es/sobre-nosotros/123 -> works
- mydomain.com/about-us/123 -> works

BUT
if I try mydomain.es/about-us/123 also works

How can I avoid this routing problem?

Thank you in advance.

**Comment by rchl** [comment] 2020-12-12 21:41
> BUT
> if I try mydomain.es/about-us/123 also works

That a known bug or a missing feature (whatever you want to call it): https://github.com/nuxt-community/i18n-module/issues/389

**Comment by enriqueaparicio-ph** [comment] 2020-12-14 08:37
I had to solve the issue using Vue Router :(

**Comment by rchl** [comment] 2020-12-14 08:46
I'll assume it's a duplicate of https://github.com/nuxt-community/i18n-module/issues/389 then and close it.
If you have a more specific issue on top of that then please create a separate issue.

**Closed as completed by rchl** 2020-12-14 08:46 UTC
Labels: feature request
