### ISSUE TITLE
Calling nuxtI18nHead generates vue-router warnings for pages without all locales enabled

### ISSUE THREAD

**Issue by rachelgould** [nuxt-modules/i18n#1071] opened 2021-02-19 16:49 UTC
### Version
nuxt-i18n: 6.20.0
nuxt: 2.14.7

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [x] universal

### Nuxt-i18n configuration
```
i18n: {
    locales: [
      {
        code: 'en-us',
        fullName: 'United States',
        iso: 'en-US',
        isCatchallLocale: true
      },
      { code: 'en-uk', fullName: 'Great Britain', iso: 'en-GB' },
      { code: 'en-au', fullName: 'Australia', iso: 'en-AU' },
      { code: 'en-eu', fullName: 'Europe', iso: 'en-EU' }
    ],
    defaultLocale: 'en-us',
    vueI18n: {
      fallbackLocale: 'en-us',
      messages
    },
    baseUrl: '...',
    seo: false // use $nuxtI18nHead method in layout instead
  },
```

### Steps to reproduce

With >2 locales enabled, create a page with a smaller subset of locales enabled. E.g. with the 4 locales enabled above, create a page with just:

```
nuxtI18n: {
    locales: ['en-us', 'en-ca']
},
```

On the page in `head()`, call `this.$nuxtI18nHead({ addSeoAttributes: true })`.

You'll see vue-router warnings for every locale that isn't enabled on this page, as `nuxtI18nHead` tries to get a route for those locales: `vue-router.esm.js?8c4f:16 [vue-router] Route with name 'SLUG___en-uk' does not exist`.

### What is Expected?

I wouldn't expect these warnings to be generated, since the `<link>` tags generated by `nuxtI18nHead` (correctly) don't link to locale routes that don't exist.

### What is actually happening?

Warnings are generated for every locale route that doesn't exist for each page calling `nuxtI18nHead`.

**Comment by rchl** [comment] 2021-02-23 22:29
Duplicate of #710

**Closed as completed by rchl** 2021-02-23 22:29 UTC
Labels: bug 🐛
