### ISSUE TITLE
Overrides do not work for messages with parameters

### ISSUE THREAD

**Issue by Jactami** [nuxt-modules/i18n#2476] opened 2023-10-04 08:56 UTC
### Environment

Operating System: Windows_NT
- Node Version: v18.17.1
- Nuxt Version: 3.7.4
- CLI Version: 3.9.0
- Nitro Version: 2.6.3
- Package Manager: pnpm@8.8.0
- Builder: -
- User Config: modules, i18n
- Runtime Modules: @nuxtjs/i18n@8.0.0-rc.4
- Build Modules: -

### Reproduction

[CodeSandbox Demo](https://codesandbox.io/p/sandbox/i18n-with-nuxt-layers-wfnrgx?file=%2Fshared-layer%2Flang%2Fen.json%3A5%2C1)

### Describe the bug

I am working on a Nuxt project using Nuxt layers and the i18n module. I have i18n messages with parameters defined in a shared layer, and I want these messages to be overwritten by the project layer. However, the messages from the shared layer are not being overwritten as expected. If the messages contain parameters, the message from the shared layer is used and not the one from the project layer. However, messages without parameters work as expected.

Here's a step-by-step description of the issue (see my [CodeSandbox Demo](https://codesandbox.io/p/sandbox/i18n-with-nuxt-layers-wfnrgx?file=%2Fshared-layer%2Flang%2Fen.json%3A5%2C1)):

1. In the shared layer, I have defined i18n messages with parameters in a JSON file. For example, in `shared-layer/lang/en.json`, I have defined the English translations.
```json
{
    "simpleHello": "Hello!",
    "personalHello": "Hello {name}!"
}
```

2. In my shared Nuxt config i linked this JSON file:
```ts
export default defineNuxtConfig({
  modules: ["@nuxtjs/i18n"],
  i18n: {
    detectBrowserLanguage: false,
    langDir: "./lang",
    locales: [{ code: "en", file: "en.json" }],
    defaultLocale: "en",
  },
});
```

3. In the project layer, I attempted to override the messages in a separate JSON file `lang/en.json` :
```json
{   
    "simpleHello": "Greetings!"
    "personalHello": "Greetings {name}!"
}
```

4. This file is registered in the Nuxt config in my project layer: 

```ts
export default defineNuxtConfig({
  extends: "./shared-layer",
  i18n: {
    langDir: "./lang",
    locales: [{ code: "en", file: "en.json" }],
  },
});
```

5. In my Vue components, I am using the `$t` function to translate my text. However, the `$t` function is using the messages from the shared layer instead of the project layer if the message includes parameters:

```html
<template>
  <div>
    <p>{{ $t('simpleHello') }}</p>
   <!-- This will print "Greetings!" (overwritten as expected) -->
    <br>
    <p>{{ $t('personalHello', { name: 'John Doe' }) }}</p>
   <!-- This will print "Hello John Doe" and not "Greetings John Doe" (not overwritten) -->
  </div>
</template>
```
 

I have searched the Nuxt i18n module documentation and GitHub issues for similar issues, but I could not find any information about my problem.

I would appreciate it if someone could help me resolve this issue.

**Comment by BobbieGoede** [comment] 2023-10-05 08:44
After testing it looks like messages with parameters are also not overwritten when a project provides multiple message files itself [reproduction here](https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-gokk2d?file=pages%2Findex.vue). 

It seems to be related to `jit` compilation, disabling it with `compilation: { jit: false }` makes the overwriting work as expected. Will be looking into what could be causing it, maybe this is cause by the way we merge objects within messages? /cc @kazupon

**Comment by BobbieGoede** [comment] 2023-11-15 22:48
Have been trying to debug this issue for a while, this issue will be fixed when https://github.com/intlify/vue-i18n-next/issues/1634 is resolved and implemented in this module. Working on making that happen!

**Closed as completed** 2023-11-16 08:45 UTC
Labels: v8, ❗ p4-important
