### ISSUE TITLE
[[ REQ ]] Nuxt 3 Support

### ISSUE THREAD

**Issue by hamzaelmaghari** [nuxt-modules/i18n#1503] opened 2022-09-02 17:33 UTC
# Please support Nuxt 3 ...

Thanks

**Comment by stafyniaksacha** [comment] 2022-09-02 22:58
The nuxt 3 version is still in development, thanks to contributors, please read https://github.com/nuxt-community/i18n-module/discussions/1287#discussioncomment-3042457

**Comment by rchl** [comment] 2022-09-03 08:37
Duplicate of #1410

**Closed as completed by rchl** 2022-09-03 08:37 UTC
