### ISSUE TITLE
DO you use rollup packages?

### ISSUE THREAD

**Issue by NarHakobyan** [nuxt-modules/i18n#2636] opened 2023-12-25 13:33 UTC
### Describe the feature

I'm always getting warnings in my console when doing install packages that the peer dependency rollup is missing.

do you use these packages?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by NarHakobyan** [comment] 2023-12-26 12:00
@kazupon just install package and check the warnings, also check the package.json file of the project

**Comment by BobbieGoede** [comment] 2024-01-30 14:55
It's unclear what the issue is, and without a reproduction we won't be able to debug it. Closing this for now, feel free to add a description and reproduction if you're still experiencing this!

**Closed as not planned by BobbieGoede** 2024-01-30 14:55 UTC
Labels: v8, need reproduction
