### ISSUE TITLE
More options env

### ISSUE THREAD

**Issue by VladislavYakonyuk** [nuxt-modules/i18n#2770] opened 2024-02-09 20:38 UTC
### Describe the feature

I would like to be able to change trace parameters of i18n using nuxt runtimeConfig:

- list of languages available for use (locales object or messages)
- default language 

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by BobbieGoede** [comment] 2024-02-13 16:58
During the build step we use the configured locales to generate routes among other things, so unfortunately it's currently not possible to make this editable at runtime. Hopefully we will be able to make this possible in the (far) future.

**Comment by BobbieGoede** [comment] 2024-02-15 12:22
Closing this as this is essentially a duplicate of https://github.com/nuxt-modules/i18n/issues/2289, if you have ideas or suggestions please comment them on that issue.

**Closed as not planned by BobbieGoede** 2024-02-15 12:22 UTC
Labels: feature request, v8

**Comment by VladislavYakonyuk** [comment] 2024-02-19 17:30
Thanks for the reply! I've come to this solution so far, which is not very pretty

```ts
const locales = [];

if (!!process.env.USE_LANGUAGE_EN || process.env.NODE_ENV === "development") {
    locales.push({
        code: "en",
        iso: "en-US",
        name: "English",
        file: "en.json"
    });
}

if (!!process.env.USE_LANGUAGE_SR || process.env.NODE_ENV === "development") {
    locales.push({
        code: "sr",
        iso: "sr-Latn",
        name: "Serbian",
        file: "sr.json"
    });
}
```
