### ISSUE TITLE
When using multiple lazy loaded files the original messages will be overwritten, but cannot be restored.

### ISSUE THREAD

**Issue by NoudH** [nuxt-modules/i18n#3089] opened 2024-09-05 20:23 UTC
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v22.2.0
- Nuxt Version:     3.13.1
- CLI Version:      3.13.1
- Nitro Version:    2.9.7
- Package Manager:  npm@10.7.0
- Builder:          -
- User Config:      devtools, modules, css, compatibilityDate, supabase, i18n, eslint
- Runtime Modules:  @nuxt/ui@2.18.4, @nuxtjs/supabase@1.4.0, @nuxtjs/i18n@8.5.2, @nuxt/eslint@0.5.5, @nuxt/fonts@0.7.2
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-qmsqbq?file=pages%2Findex.vue

### Describe the bug

When using multiple lazy loaded files the original messages will be overwritten, but cannot be restored.

Imagine the following scenario:

en.json
```json
{
  "welcome": "welcome!"
}
```

en-GB.json
```json
{
  "welcome": "Test!"
}
```

nuxt.config.ts
```typescript
...
i18n: {
    lazy: true,
    langDir: 'lang',
    locales: [
      {
        name: 'English (American)',
        locale: 'en-US',
        code: 'en-US',
        files: ['en.json'],
      },
      {
        name: 'English (British)',
        locale: 'en-GB',
        code: 'en-GB',
        files: ['en.json', 'en-GB.json'],
      },
    ],
  },
...
```

Originally, when first navigating to the page the message will read "welcome!", then when switching to en-GB it will switch to "Test!" (So far so good). However, when switching back to en-US the text will still read "Test!". When force reloading the page it will turn back to "welcome!".

### Expected behavior

When swapping back to a locale that was previously overwritten/inherited the original messages should be restored.

**Comment by BobbieGoede** [comment] 2024-09-22 20:15
This has been resolved in the next major version (alpha currently), updated reproduction: https://stackblitz.com/edit/github-qmsqbq-ayzaed?file=package.json. We're hard at work to have a release candidate ready soon!

**Comment by BobbieGoede** [comment] 2024-09-26 09:35
This will be resolved with https://github.com/nuxt-modules/i18n/pull/3137 since I've fixed the issue upstream! Here's an updated reproduction with using a preview release https://stackblitz.com/edit/github-qmsqbq-ayzaed?file=package.json,nuxt.config.ts,lang%2Fen-GB.json

**Closed as completed** 2024-09-26 09:36 UTC
Labels: upstream
