### ISSUE TITLE
[NEXT] Deploys to Edge Targets are failing `Cannot read properties of undefined (reading 'FunctionTranslate')`

### ISSUE THREAD

**Issue by warflash** [nuxt-modules/i18n#1500] opened 2022-08-29 18:25 UTC
### Version
@nuxtjs/i18n: 8.0.0-alpha.0-27694154.4d62fb4
nuxt: 3.0.0-rc.8

### Nuxt configuration

 - [ ] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [x] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration

see repro

### Reproduction Link

https://stackblitz.com/edit/github-bhlcxt?file=pages%2Findex.vue

### Steps to reproduce

NITRO_PRESET=cloudflare yarn build
miniflare .output/server/index.mjs --site .output/public

### What is Expected?

Deploys to edge targets like netlify edge, cloudflare workers and pages as well as vercel edge should go through succesfully

### What is actually happening?

`[mf:err] TypeError: Cannot read properties of undefined (reading 'FunctionTranslate')`
...
See repro above

**Comment by oleghalin** [comment] 2022-11-28 10:15
Any updates on this? Facing only in --local wrangler env

**Comment by kazupon** [comment] 2023-02-18 10:43
I think this issue is fixed in beta version.
so close

**Closed as not planned by kazupon** 2023-02-18 10:43 UTC
Labels: bug 🐛, v8

**Comment by dargmuesli** [comment] 2023-02-23 04:49
For me, the issue is not fixed. I get the following error, notice the mention of `devtools`:

```
[mf:err] /tmp/tmp-714541-dPke2bl5SzTx/index.js:16499
    const translateDevTools = createDevToolsHook(devtoolsIf.IntlifyDevToolsHooks.FunctionTranslate);
                                                                                 ^

TypeError: Cannot read properties of undefined (reading 'FunctionTranslate')
    at style_0 (/mnt/data/WorkingDirectory/Git/dargmuesli/jonas-thelemann/dargmuesli/trapparty/nuxt/.output/server/mnt/data/WorkingDirectory/Git/dargmuesli/jonas-thelemann/dargmuesli/trapparty/nuxt/node_modules/.pnpm/@intlify+core-base@9.2.2/node_modules/@intlify/core-base/dist/core-base.cjs.prod.js:424:93)
    at /mnt/data/WorkingDirectory/Git/dargmuesli/jonas-thelemann/dargmuesli/trapparty/nuxt/.output/server/mnt/data/WorkingDirectory/Git/dargmuesli/jonas-thelemann/dargmuesli/trapparty/nuxt/.nuxt/dist/server/_nuxt/dashboard-styles.a7085c71.mjs:2:17
    at /tmp/tmp-714541-dPke2bl5SzTx/index.js:35631:3
    at Script.runInContext (node:vm:140:12)
    at VMScriptRunner.runAsScript (/home/jonas/.npm/_npx/32026684e21afda6/node_modules/@miniflare/runner-vm/src/index.ts:26:12)
    at VMScriptRunner.run (/home/jonas/.npm/_npx/32026684e21afda6/node_modules/@miniflare/runner-vm/src/index.ts:88:12)
    at Miniflare.#reload (/home/jonas/.npm/_npx/32026684e21afda6/node_modules/@miniflare/core/src/index.ts:790:42)
    at Miniflare.getPlugins (/home/jonas/.npm/_npx/32026684e21afda6/node_modules/@miniflare/core/src/index.ts:1033:5)
    at createServer (/home/jonas/.npm/_npx/32026684e21afda6/node_modules/@miniflare/http-server/src/index.ts:362:19)
    at startServer (/home/jonas/.npm/_npx/32026684e21afda6/node_modules/@miniflare/http-server/src/index.ts:469:18)
```

**Comment by dargmuesli** [comment] 2023-02-23 05:12
Ah, nvm, the error originated from `@intlify/eslint-plugin-vue-i18n` having dependencies on `v9.2`.
