### ISSUE TITLE
Translating a message in a non-default language with `lazy: true` will fail

### ISSUE THREAD

**Issue by TheAlexLichter** [nuxt-modules/i18n#2650] opened 2024-01-03 18:16 UTC
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0
- Build Modules:    -

### Reproduction

[will link in 1 sec](https://stackblitz.com/edit/nuxt-i18n-issues-2650?file=nuxt.config.ts,app.vue,locales%2Fen.json)

### Describe the bug

When translating a message into a language which is not the default language via `$t` or `t`, e.g. `$t('welcome', undefined, { locale: 'de' })` but lazy loading the language, the translation will fail with the message `[intlify] Not found 'welcome' key in 'de' locale messages.`

I'd expect that the language would be loaded instead.

**Comment by rchl** [comment] 2024-01-03 22:24
Duplicate of #2044 and #740

**Closed as not planned by rchl** 2024-01-03 22:24 UTC
Labels: pending triage
