### ISSUE TITLE
Error on the latest nuxt 2.15.0

### ISSUE THREAD

**Issue by kissu** [nuxt-modules/i18n#1065] opened 2021-02-15 13:36 UTC
### Version
nuxt-i18n: 6.20.0
nuxt: 2.15.0

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [ ] universal
 - [x] spa

### Nuxt-i18n configuration
I don't think that this is relevant since it was perfectly working before but here we are.
```
[
  'nuxt-i18n',
  {
    defaultLocale: 'fr',
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'detected_locale',
      fallbackLocale: 'fr',
    },
    strategy: 'no_prefix',
    vueI18n: {
      fallbackLocale: 'fr',
      silentFallbackWarn: process.env.NODE_ENV === 'production',
      silentTranslationWarn: process.env.NODE_ENV === 'production',
      warnHtmlInMessage: 'error',
      escapeParameterHtml: true,
    },
    vueI18nLoader: true,
    vuex: {
      syncLocale: true,
      syncRouteParams: false,
    },

    lazy: true,
    langDir: 'locales/',
    locales: [
      {
        code: 'en',
        file: 'en.json',
        iso: 'en',
      },
      {
        code: 'fr',
        file: 'fr.json',
        iso: 'fr',
      },
    ],
  },
],
```

### Reproduction Link
Not sure if it's needed in this case.

### Steps to reproduce
I was in `nuxt-i18n` at `6.13.2`, I did upgraded nuxt to the latest version `@2.15.0` (from `2.14.6`). It's now not working.
I upgraded `nuxt-i18n` to the latest `6.20.0` but it is not working neither.

### What is Expected?
I expected to have it work as before.

### What is actually happening?
![image](https://user-images.githubusercontent.com/5133074/107952561-37fe6e00-6f9a-11eb-9309-555ffa7fd3d1.png)

**Comment by rchl** [comment] 2021-02-15 13:43
Duplicate of #1063

Just released https://github.com/nuxt-community/i18n-module/releases/tag/v6.20.1 with a fix.

**Closed as completed by rchl** 2021-02-15 13:43 UTC
Labels: bug 🐛

**Comment by kissu** [comment] 2021-02-15 13:49
Thanks !
Tried it and I found another bug. Not sure if I missed a breaking change update while going from `6.13.2` to `6.20.1`.
![image](https://user-images.githubusercontent.com/5133074/107954526-d8559200-6f9c-11eb-99c0-7fb28ec9d5f7.png)

**Comment by rchl** [comment] 2021-02-15 13:54
This error is about CSS Loader and not VueLoader so I think it's a separate issue that is not related to this module.

The Nuxt 2.15.0 change that broke nuxt-i18n is likely to break other modules in a similar manner.

**Comment by kissu** [comment] 2021-02-15 13:55
Ooops, indeed skipped the CSS line ! Thank you. 🙏🏻
