### ISSUE TITLE
Fallback locale not working with mixed code (language & language+region)

### ISSUE THREAD

**Issue by Archetipo95** [nuxt-modules/i18n#3012] opened 2024-07-03 22:19 UTC
### Environment

Everywhere

### Reproduction

https://github.com/nuxt/movies/issues/66
[movies.nuxt.space](https://movies.nuxt.space/)

### Describe the bug

Navigate to the officially hosted site [movies.nuxt.space](https://movies.nuxt.space/)
Change language to Español (for example) and try to search for TENET movie (or any other).
Looks like this happens for all words that use interpolation, that are not present in the selected language dictionary.

### Additional context

If you rename the code `es-ES` to just `es` the fallback works

**Comment by BobbieGoede** [comment] 2024-07-31 10:43
I'm unable to reproduce this using the live website, can you reproduce this issue in a minimal reproduction project?

**Comment by Archetipo95** [comment] 2024-08-05 14:33
@BobbieGoede there was a fix with this PR, but the problem is not solved.
https://github.com/nuxt/movies/pull/67/files
If u pick the code before this PR (they just added the missing translations) you can reproduce the problem locally too

**Comment by BobbieGoede** [comment] 2024-08-05 15:33
I have opened https://github.com/nuxt/movies/pull/71 that should resolve your issue, no `fallbackLocale` was set.

>If you rename the code es-ES to just es the fallback works

I was unable to replicate this behavior, I'm not sure how that would have worked 🤔

**Comment by BobbieGoede** [comment] 2024-08-05 16:34
I'll close this issue as this should be resolved with the configuration changes in https://github.com/nuxt/movies/pull/71, I suppose the docs could explain this better but we intend to improve and unify Vue I18n and Nuxt I18n configuration soon anyway.

Let me know if you have any questions, if the PR doesn't resolve the issue we can always reopen, just trying to get the issue count down 😅

**Closed as not planned by BobbieGoede** 2024-08-05 16:34 UTC
Labels: v8, v9
