### ISSUE TITLE
Cannot create property 'isRootInsert' on string with slots syntax.

### ISSUE THREAD

**Issue by Gmiliuta** [nuxt-modules/i18n#1027] opened 2021-01-14 13:20 UTC
Hi, I want to implement dynamic component which generates template as per passed Props using component interpolation approach. 
https://kazupon.github.io/vue-i18n/guide/interpolation.html#slots-syntax-usage

The issue I am having is that if you load the example page directly (webpage.com/example), it works, however if you navigate to it from example.com or any other page it triggers errors:

- TypeError: Cannot create property 'isRootInsert' on string 
- [Vue warn]: Error in nextTick: "TypeError: Cannot create property 'isRootInsert' on string

Been trying to use approach described in this issue #945 , but no luck. 

**Error:** 
<img width="1440" alt="Screenshot 2021-01-14 at 13 41 21" src="https://user-images.githubusercontent.com/53524766/104594528-91107480-5671-11eb-8d66-133a1bf95570.png">

**Working example when page is loaded directly or reloaded:**
<img width="504" alt="Screenshot 2021-01-14 at 14 08 50" src="https://user-images.githubusercontent.com/53524766/104594873-109e4380-5672-11eb-8f7a-c8d01264c756.png">

**Package.json:**
<img width="341" alt="Screenshot 2021-01-14 at 13 54 51" src="https://user-images.githubusercontent.com/53524766/104594754-e6e51c80-5671-11eb-83ad-0d1c270336ed.png">

**Module config:**
<img width="366" alt="Screenshot 2021-01-14 at 13 54 15" src="https://user-images.githubusercontent.com/53524766/104594964-362b4d00-5672-11eb-82d5-708eeb4354bd.png">

**Component and translation JSON object:**
<img width="1783" alt="Screenshot 2021-01-14 at 13 52 24" src="https://user-images.githubusercontent.com/53524766/104595141-75599e00-5672-11eb-827c-e7a568f4300a.png">

Some additional info:

- Did not work with functional components, nor without property decorators. In all cases same errors.

Been stuck on this for a day now, without any idea what might be causing this behaviour.  Any help will be appreciated and thanks for looking into this! :)

**Comment by rchl** [comment] 2021-01-14 14:55
I'm not really sure what this is about but it's not strictly related to this module. Maybe a weird interaction between `vue-i18n` and Vue.

Maybe try to wrap the `i18n` element in an extra node?

Or google the error and see if you can figure out the problem from there. I see that there are some existing problems like that but generally should be fixed in recent Vue versions so maybe your project is pulling older versions somehow.

Won't be able to help more without a reproduction repo.

**Comment by Gmiliuta** [comment] 2021-01-15 08:45
@rchl thanks for quick answer.

Wrapping i18n element with another node still causes an error.

**Comment by BlowAlone** [comment] 2021-02-01 07:14
Have the same issue after migrating codebase to typescript (nuxt-property-decorator).
I guess it can be related to named slots and functional components  + TS: https://github.com/vuejs/vue/issues/4589
Or this one: https://github.com/vuejs/vue/issues/9372

**Comment by BlowAlone** [comment] 2021-02-03 08:56
@Gmiliuta I understood what the problem is.
When you navigate to another page, event routeChanged is fired, which under normal circumstances is fired from the root component. 
![image](https://user-images.githubusercontent.com/23696883/106722001-79942e00-6616-11eb-8e97-87b4c6d16fd5.png)

If it is called from another component, it may indicate that this component is without a decorator ```@Component```.

@rchl So, it seems the issue has been resolved

**Closed as completed** 2021-02-07 07:30 UTC
Labels: need more info
