### ISSUE TITLE
Does nuxtjs3 support it?

### ISSUE THREAD

**Issue by todaynogada** [nuxt-modules/i18n#1425] opened 2022-04-14 18:48 UTC
**nuxt.config.ts**

    modules: [
        '@nuxtjs/i18n',
    ],

**error code**

 ERROR  Error compiling template:  {                                                                                                                   03:43:57
  src: 'C:\\project\\temp\\main\\node_modules\\@nuxtjs\\i18n\\src\\templates\\plugin.utils.js',
  fileName: 'nuxt-i18n\\plugin.utils.js',
  options: {
    Constants: {
      COMPONENT_OPTIONS_KEY: 'nuxtI18n',
      STRATEGIES: [Object],
      REDIRECT_ON_OPTIONS: [Object]
    },
    nuxtOptions: {
      isUniversalMode: false,
      trailingSlash: undefined
    },
    options: {
      vueI18n: {},
      vueI18nLoader: false,
      locales: [],
      defaultLocale: '',
      defaultDirection: 'ltr',
      routesNameSeparator: '___',
      defaultLocaleRouteNameSuffix: 'default',
      sortRoutes: true,
      strategy: 'prefix_except_default',
      lazy: false,
      langDir: null,
      rootRedirect: null,
      detectBrowserLanguage: [Object],
      differentDomains: false,
      baseUrl: '',
      vuex: [Object],
      parsePages: true,
      pages: {},
      skipSettingLocaleOnNavigate: false,
      onBeforeLanguageSwitch: [Function: onBeforeLanguageSwitch],
      onLanguageSwitched: [Function: onLanguageSwitched],
      normalizedLocales: [],
      localeCodes: []
    }
  },
  filename: 'nuxt-i18n\\plugin.utils.js',
  dst: 'C:/project/temp/main/.nuxt/nuxt-i18n/plugin.utils.js'
}

Can I use vue-i18n module without using @nuxtjs/i18n module for nuxtjs3?

**Comment by jamesallan93** [comment] 2022-04-16 03:44
I'm facing the same thing, it's not working.

**Comment by brolnickij** [comment] 2022-04-17 14:04
yes, this library does not yet work for nuxt 3 (even in "next" branch)
https://github.com/nuxt-community/i18n-module/issues/1416
https://github.com/nuxt-community/i18n-module/issues/1410

---

P.S. here the man suggested a solution that should work, but it didn't work for me https://github.com/nuxt-community/i18n-module/issues/1416#issuecomment-1087966878

**Comment by rchl** [comment] 2022-04-17 20:49
Duplicate of #1410

**Closed as completed by rchl** 2022-04-17 20:49 UTC
