### ISSUE TITLE
Nuxt i18n + differentDomains + Apache Proxy

### ISSUE THREAD

**Issue by bcadu** [nuxt-modules/i18n#2339] opened 2023-08-23 15:54 UTC
### Environment

- Operating System: Linux
- Node Version:     v16.18.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@8.19.2
- Builder:          vite
- User Config:      devtools, modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.3

### Reproduction

We need to enable the differentDomains option of i18n module but we have a redirection issue.

The code is here https://stackblitz.com/edit/github-kudpru

And we have this small Apache config

```
<VirtualHost *:80>
    ServerName fr.localhost
    ServerAlias en.localhost
    ServerAlias es.localhost

    ProxyPass / http://localhost:3000/
    ProxyPassReverse / http://localhost:3000/
</VirtualHost>
```

(I precise we are not in https to simpify the reproduction)

### Describe the bug

On http://fr.localhost/ it's ok with the correct translation.

On http://en.localhost/ , We're redirect to http://en.localhost/:/en.localhost   with this message "Page not found: /:/en.localhost"

Same issue with http://es.localhost/  => redirection to http://es.localhost/:/es.localhost

The nuxt-config file is minimalist:
```
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ["@nuxtjs/i18n"],
  i18n: {
    detectBrowserLanguage: false,
    //strategy: "no_prefix",
    defaultLocale: "en",
    locales: [
      {
        code: "fr",
        domain: "fr.localhost",
        file: "fr-FR.json",
      },
      {
        code: "en",
        domain: "en.localhost",
        file: "en-GB.json",
      },
      {
        code: "es",
        domain: "es.localhost",
        file: "es.json",
      },
    ],
    langDir: "lang",
    lazy: true,
    differentDomains: true,
  },
})
```

If we activate this option 

`strategy: "no_prefix"`

The same issue occurs for http://fr.localhost/ 

Is there something wrong in the config or is it a bug ?

### Logs

```shell
> start
> node .output/server/index.mjs

Listening http://[::]:3000
[Vue Router warn]: No match found for location with path "/:/en.localhost"
[Vue Router warn]: No match found for location with path "/:/en.localhost"
[Vue Router warn]: No match found for location with path "/:/en.localhost"
[Vue Router warn]: No match found for location with path "/:/en.localhost"
[Vue Router warn]: No match found for location with path "/:/en.localhost"
[Vue Router warn]: No match found for location with path "/:/en.localhost"
[Vue Router warn]: No match found for location with path "/:/en.localhost"
[Vue Router warn]: No match found for location with path "/:/en.localhost
```

**Comment by melaniehuet** [comment] 2023-09-01 10:14
Reproduced with the similar apache conf on port 80, to serve a localhost:3000 Nuxt app. I have the same issue. Seems to be a problem when there is no port in domain key. The i18n module is trying to redirect to the domain followed by ":"
It's working with these configurations:

```
Listen 8080
<VirtualHost *:8080>
  ServerName mydomain.uk
  ServerAlias mydomain.fr

  ProxyPass / http://localhost:3000/
  ProxyPassReverse / http://localhost:3000/
</VirtualHost>
```

and

```
export default defineNuxtConfig({
  devtools: { enabled: true },
  pages: true,
  modules: [
    '@nuxt/devtools',
    [
      '@nuxtjs/i18n',
      {
        legacy: false,
        differentDomains: true,
        detectBrowserLanguage: false,
        messages: {
          en: {
            welcome: 'Welcome'
          },
          fr: {
            welcome: 'Bienvenue'
          }
        },
        locales: [
          {
            code: 'en',
            domain: 'mydomain.uk:8080'
          },
          {
            code: 'fr',
            domain: 'mydomain.fr:8080'
          }
        ]
      },
    ]
  ]
})
```

**Comment by a-posokhov** [comment] 2023-09-11 09:15
I have the same issue even if I don't use proxy, but run nuxt in dev mode on port 80 locally.

**Comment by BobbieGoede** [comment] 2023-09-20 21:25
This issue is a bit difficult for me to replicate locally, can you check if you're still experiencing this issue after installing the edge channel (you can install it as an alias like so: `npm i -D @nuxtjs/i18n@npm:@nuxtjs/i18n-edge`)? 

It looks similar to an issue that was fixed by this PR https://github.com/nuxt-modules/i18n/pull/2363.

**Comment by bcadu** [comment] 2023-09-21 07:14
Hi @BobbieGoede,

It looks ok when I install i18n with your command 

`
npm i -D @nuxtjs/i18n@npm:@nuxtjs/i18n-edge
`

I have this line in the package.json:

`
"@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge@^8.0.0-rc.4-28252997.568c274"
`

There is no more redirection as before.
Thank you very much.

(But if I install "@nuxtjs/i18n": "^8.0.0-rc.4" I still have the problem.)

Do you have any idea when a stable version of @nuxtjs/i18n will be released?

**Comment by BobbieGoede** [comment] 2023-09-21 07:27
That's good to hear! Any fixes will be included in the next release of course.

> Do you have any idea when a stable version of @nuxtjs/i18n will be released?

We will likely have some more release candidates before stable release, still plenty of open issues (bugs and regressions) to work through 😅

**Closed as completed by BobbieGoede** 2023-09-21 07:27 UTC
Labels: v8, pending triage, scope: domains
