### ISSUE TITLE
Incorrect locale when page entered without slash after language slug.

### ISSUE THREAD

**Issue by isuke01** [nuxt-modules/i18n#1378] opened 2022-01-13 17:27 UTC
### Version
@nuxtjs/i18n: v7.2.0
nuxt:  v2.15.8

### @nuxtjs/i18n configuration
```
      [
        '@nuxtjs/i18n',
        {
          strategy: 'prefix_except_default',
          detectBrowserLanguage: false,
          baseUrl: 'http://test.local:8080',
          locales: [
            {
              name: 'English',
              code: 'en',
              iso: 'en-GB'
            },
            {
              name: 'Norwegian',
              code: 'nb',
              iso: 'nb-NO'
            }
          ],
         
          vuex: {
            preserveState: true,
            //syncLocale: true https://i18n.nuxtjs.org/migrating
          },
          lazy: false,
          defaultLocale: 'nb',
        }
      ]
```

### What is Expected?
   The default locale is **NB**. 
   When I enter the page with both url `http://test.local:8080/en` and `http://test.local:8080/en/` I'd like to have  locale **EN**

### What is actually happening?
When I enter the page: `http://test.local:8080/en` locale is **NB** 
When I enter the page `http://test.local:8080/en/` (With slash at the end) Locale is **EN**
When I enter the page with any deeper link like `http://test.local:8080/en/test` or `http://test.local:8080/en/test/`  in both cases locale is set correctly as **EN**

The only one time with the issue appear is when I enter the home page without slash. I have tried to set `router: { trailingSlash: true }` But in that case the error is all the way around with slash it is **NB** without **EN**, and as previously no issues in deeper url's.

Before I used `nuxtjs/i18n` 6.6... with Nuxt 2.0.something and It was correct as far as I remember and how it works now.

The only solution that I found is temporary server-middleware to remove or add  (depend of route setting) last slash if user enter home page.

### Reproduction
[https://codesandbox.io/s/musing-frost-99zbf](https://codesandbox.io/s/musing-frost-99zbf) Just try `.../en` and `.../en/` inside code sandbox. it print out the current locale. I also added simple links to easy click through the issue.

**Comment by rchl** [comment] 2022-01-14 10:40
You have a `_.vue` route in the project which captures the `/en` path and treats it as a slug `en` using the default locale NB.

You can have a look at the generated routes in `.nuxt/router.js` to better understand why it's happening:

```js
  routes: [{
    path: "/en/*",
    component: _f0fe2a6e,
    name: "all___en"
  }, {
    path: "/*",
    component: _f0fe2a6e,
    name: "all___nb"
  }],
```

Only the second route will catch the `/en` path.

Also this is a duplicate of #632

**Closed as completed by rchl** 2022-01-14 10:40 UTC

**Comment by rchl** [comment] 2022-01-14 10:44
You can experiment with Nuxt's `extendRoutes` to add a redirect routes from `/en` to `/en/` etc.

**Comment by isuke01** [comment] 2022-01-14 10:47
For now I'll just make server-middleware that redirects in that only one case to correct one like `/en/` to `/en` or otherway around - depend of the ` router: { trailingSlash ....}` setting.
Later I'll post my solution, maybe someone can find it helpfull :)
