### ISSUE TITLE
Lazy-loading doesn't allow translating in different locale

### ISSUE THREAD

**Issue by mtdvlpr** [nuxt-modules/i18n#2044] opened 2023-05-07 10:56 UTC
### Environment

- Operating System: Linux
- Node Version:     v18.15.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  yarn@3.5.1
- Builder:          vite
- User Config:      srcDir, ssr, telemetry, typescript, build, imports, router, sourcemap, modules, i18n, vite, nitro, runtimeConfig
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.10, @vueuse/nuxt@10.1.2, nuxt-lodash@2.4.1, @pinia/nuxt@0.4.9, nuxt-electron@0.4.5, ()
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-brvbfm?file=app.vue

### Describe the bug

With the option `lazy: true`, you can't translate anything in a locale other than the current. 
`$i18n.t('welcome', 1, { locale: 'nl' })` doesn't work.

### Additional context

I get that the locale might have to be imported manually first, but there should at least be an option to do so.

### Logs

```shell
[intlify] Not found 'welcome' key in 'nl' locale messages.
```

**Comment by kazupon** [comment] 2023-05-09 06:38
Thank you for your reporting!

Unfortunately, When the locale options of `t` (`$t`) cannot handle lazy-loading.
We need to extend these function (e.g. proxy or wrap?)

**Comment by rchl** [comment] 2024-01-03 22:25
Duplicate of the v7 issue #740 but it applies the same to Nuxt 3 also.

**Closed as not planned by rchl** 2024-01-03 22:25 UTC
Labels: v8, 🔨 p3-minor-bug, scope: locales
