### ISSUE TITLE
When there are Chinese characters in the route param, the route navigation does not behave as expected

### ISSUE THREAD

**Issue by dongnaebi** [nuxt-modules/i18n#2439] opened 2023-09-23 10:01 UTC
### Environment

- Operating System: Windows_NT
- Node Version:     v18.16.1
- Nuxt Version:     3.7.3
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  pnpm@7.13.6
- Builder:          -
- User Config:      modules, colorMode, gtag, googleFonts, i18n, routeRules, nitro, build
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @nuxtjs/color-mode@3.3.0, @nuxtjs/i18n@8.0.0-rc.4-28252997.568c274, @nuxt/content@2.8.2, nuxt-gtag@1.1.1, @nuxtjs/google-fonts@3.0.2
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-uxy1hj?file=pages%2Fsearch%2F%5Bkeyword%5D.vue

#### Reproduction Steps
- Go search page
- Enter English word and click Search button
- Enter another English word and click Search button again
- Click "Go back" button twice to Home page
- Go search page again
- Enter Chinese word(你好) and click Search button
- Enter another Chinese word(有问题) and click Search button again
- Click "Go back"

At this time, no matter how many times I click, I can’t return to the home page.

Not only that, but if I enter any other text to search, nothing happens.

If I delete `strategy: 'no_prefix'` in `nuxt.config.ts`, it's work.

### Another Reproduction

https://stackblitz.com/edit/nuxt-starter-jrhocc?file=pages%2Fsearch%2F%5Bkeyword%5D.vue

#### Reproduction Steps
- Click the button to switch language, and make sure there is a cookie with key `lang`
- Click "Go search page"
- Enter something and click Search button

Nothing to change, if set `detectBrowserLanguage.useCookie` to false, it's work, or if the route param is an English word, it's work too.

### Describe the bug

See Reproduction Steps

**Comment by BobbieGoede** [comment] 2023-10-24 13:32
This issue seems to be fixed by #2518, updated reproduction [here](https://stackblitz.com/edit/nuxt-starter-prwwt4?file=package.json,nuxt.config.ts). Let me know if you're still experiencing this issue after installing the edge channel!

**Closed as completed by BobbieGoede** 2023-10-24 13:32 UTC
Labels: v8, 🔨 p3-minor-bug, scope: routing

**Comment by dongnaebi** [comment] 2023-10-24 13:42
It's work, thanks
