### ISSUE TITLE
secondary language home page shows incorrect locale

### ISSUE THREAD

**Issue by rodsouto** [nuxt-modules/i18n#1067] opened 2021-02-17 02:05 UTC
### Version
nuxt-i18n:  6.20.1
nuxt: 2.15.0

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [x] universal
 - [] spa

### Nuxt-i18n configuration
```
i18n: {
    parsePages: false,
    locales: [
      {
        code: 'en',
        name: 'EN',
      },
      {
        code: 'es',
        name: 'ES',
      },
    ],
    defaultLocale: 'es',
    vueI18n: {
      fallbackLocale: 'es',
    },
  }
```

### Reproduction Link

I have created a mini test case based in the original code of our website, the repository can be found here https://github.com/rodsouto/nuxt-error

### Steps to reproduce

run `yarn generate`

### What is Expected?

in `dist/en/index.html` you should see `Locale: en`

### What is actually happening?

In `dist/en/index.html` you see `Locale: es`. 

If you run `yarn start` and go to `http://localhost:3000/en` you will see `Locale: en`  but `Servicio 1` in spanish (it should show `Service 1`)

If you run `yarn dev` and then go to `http://localhost:3000/en` it correctly shows `Locale: en` and `Service 1`

 `dist/en/services/service-1/index.html` shows correctly `Locale: en`, so this error only occurs in the english home page
 
Any idea about what might cause this problem?

**Comment by rchl** [comment] 2021-02-17 07:15
The generated routes for a dynamic route like that (`_.vue`) looks like this:

```
  routes: [{
    path: "/en/*",
    component: _3ecbae89,
    name: "all___en"
  }, {
    path: "/*",
    component: _3ecbae89,
    name: "all___es"
  }],
```

That means that `/en` route will be handled by the `all___es` route (in static mode at least).

Some kind of workaround would be to set `router { trailingSlash: true }` in nuxt config but that seems to trigger a problem when generating the `/` route.

I haven't dug deeper to see where the problem is exactly and how it should be fixed...

**Comment by rodsouto** [comment] 2021-02-18 16:40
not the best solution but this allows to generate the route `/` with `trailingSlash: true` 👍

```js
router: {
    trailingSlash: true,
    extendRoutes(routes) {
      const route = routes.filter((route) => route.name === 'all').slice(0, 1)[0]

      if (route !== undefined) {
        const homeRoute = Object.assign({}, route)

        homeRoute.name = 'home'
        homeRoute.path = '/'

        routes.push(homeRoute)
      }
    },
  },
```

**Comment by vanling** [comment] 2021-03-25 22:44
@rodsouto Thanks 👍  my homepage was not showing up. +) this saves me some duplication

**Closed as completed** 2021-06-09 22:50 UTC
Labels: bug 🐛, scope: ssg
