### ISSUE TITLE
Named formatting display {param} in build

### ISSUE THREAD

**Issue by JulienHenrotin** [nuxt-modules/i18n#2040] opened 2023-05-04 14:32 UTC
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.14.1
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  npm@9.3.1
- Builder:          vite
- User Config:      modules
- Runtime Modules:  @nuxt/devtools@0.4.5, @nuxtjs/i18n@8.0.0-beta.11
- Build Modules:    -
------------------------------

### Reproduction

[Reproduction gitHub](https://github.com/JulienHenrotin/test_nuxt_i18n)
[Reproduction stackblitz](https://stackblitz.com/github/JulienHenrotin/test_nuxt_i18n)

```
npm i
npm run build
node .output/server/index.mjs
```

### Describe the bug

Hi ! 

I have a problem with named formatting in i18n when I build my project for production.

In my template I have something like that : 
`<p>{{ $t('hello', { param: 'World' }) }}</p>`
And in my locale file : 
`    "hello": "bonjour {param}",`

After build my project the result is  : 
> bonjour {param}

In dev mode no problem I get "bonjour World"

I hope you can enlighten me I don’t see where the problem comes from 😶‍🌫️

### Additional context

What I tried : 

- activate log on i18n config -> nothing suspicious
- use useI18n() to get translation in script part -> same thing than template part
- try nuxtjs/i18n-edge
- build my project on production server with docker 
- Create a project with only I18n modules (link in reproduction part)

**Comment by default64bit** [comment] 2023-05-08 09:22
Possible duplicate of [#1569](https://github.com/nuxt-modules/i18n/issues/1569)

**Comment by ineshbose** [comment] 2023-05-09 09:00
Thank you for opening the issue - it seems like a duplicate of #1569, so lets track status there.

**Closed as not planned by ineshbose** 2023-05-09 09:00 UTC
Labels: v8, pending triage
