### ISSUE TITLE
v9 rc2 useTranslation not found

### ISSUE THREAD

**Issue by alexcroox** [nuxt-modules/i18n#3179] opened 2024-10-14 16:13 UTC
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-47lmie?file=package.json,nuxt.config.ts,i18n%2Fi18n.config.ts,server%2Fapi%2Ftest.get.ts,app%2Fpages%2Findex.vue

### Describe the bug

I'm using the latest Nuxt with v4 compatability. I'm also using v9 rc2 of @nuxtjs/i18n.

Since upgrading this i18n I'm getting the fatal error on my APIs for `useTranslation` not being available. See repro above for a demo of this.

**Comment by BobbieGoede** [comment] 2024-11-02 16:01
The `i18n.config.ts` file is meant for vue-i18n options only, sorry for the confusion! I'm unable to reproduce your issue after moving the nuxt i18n specific options to the nuxt config file, here's your modified reproduction https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-pa8wnb?file=nuxt.config.ts.

Closing this for now, let me know if you have any questions!

**Closed as not planned by BobbieGoede** 2024-11-02 16:01 UTC
Labels: pending triage
