### ISSUE TITLE
Netlify SSR not rendering translations

### ISSUE THREAD

**Issue by Rigo-m** [nuxt-modules/i18n#2111] opened 2023-05-26 13:04 UTC
### Environment

https://github.com/Rigo-m/i18n-netlify-reproduction

### Reproduction

https://github.com/Rigo-m/i18n-netlify-reproduction
https://timely-dolphin-6482c9.netlify.app/

### Describe the bug

When first loading the page via SSR you don't see the translation, you see its key, if you navigate in SPA more (via NuxtLink) translations get loaded correctly

**Comment by Rigo-m** [comment] 2023-05-26 13:06
Maybe related to what some people were experiencing in #2097 comments

**Comment by MorevM** [comment] 2023-05-27 14:46
I experience this issue (or a similar one) as well, one note: local (per-component) translations using `const { t } = useI18n();` are displayed fine in my case (`1` on the image below), but the global `$t('...')` is output as key during SSR and becomes a real string after hydration (`2` on the image).

![i18n](https://github.com/nuxt-modules/i18n/assets/49679666/4fcb7664-5061-4113-b156-5e2bf33b9b3b)

**Comment by Rigo-m** [comment] 2023-05-28 13:36
Yeah i was using $t in templates actually, thanks for restricting the scope of the issue

**Comment by rudolfbyker** [comment] 2023-06-08 16:00
I have the same (or very similar) issue. Repro here: https://stackblitz.com/edit/github-svtdnq?file=app.vue

**Comment by josephmcg** [comment] 2023-06-15 07:25
> I experience this issue (or a similar one) as well, one note: local (per-component) translations using `const { t } = useI18n();` are displayed fine in my case (`1` on the image below), but the global `$t('...')` is output as key during SSR and becomes a real string after hydration (`2` on the image).

Thank you! This is a great fix in the meantime

**Comment by terwer** [comment] 2023-06-16 15:05
https://blog.terwer.space/

vercel ssr also not work here, nuxt 3.5.3

**Comment by josephmcg** [comment] 2023-06-19 08:58
I switched everything to `const { t } = useI18n()`, but I still see a flash of untranslated content on Netlify SSR.

**Comment by josephmcg** [comment] 2023-06-22 05:28
I resolved this by reverting to "8.0.0-beta.10" and using legacy config options

**Comment by voj-tech-j** [comment] 2023-07-03 21:16
> I resolved this by reverting to "8.0.0-beta.10" and using legacy config options

Would you be so kind and provide an example of the config options? I cannot get it working...

**Comment by josephmcg** [comment] 2023-07-04 00:07
sure, let me know if this works for you. I'm only using one locale (en) at the moment, but wanted to handle this stuff in advance

---
`i18n.config.ts`
```ts
import { I18nOptions } from '@nuxtjs/i18n/dist/runtime/composables'

const options: I18nOptions = {
  locale: 'en',
  fallbackLocale: 'en',
  messages: {
    en: {
    ...
    }
  }
}

export default options
```
---
`nuxt.config.ts`
```ts
import i18nConfig from './i18n.config'

export default defineNuxtConfig({
...
i18n: {
    locales: ['en'],
    defaultLocale: 'en',
    vueI18n: i18nConfig,
  },
})
```

**Comment by voj-tech-j** [comment] 2023-07-18 13:20
Thank you @josephmcg , it does not unfortunately... However I switched to Amplify and everything works just great :)

**Comment by awacode21** [comment] 2023-08-01 12:20
for me it is also not working with local translation.
It's also not only with netlify. I am experiencing it with Vercel. I think the host is irrelevant. The problem is related to SSR.
When you use SSR you get an hydration mismatch cause it outputs the key ons server and the translated text on client.
This hydration mismatch happens because of this error:

"The message format compilation is not supported in this build. Because message compiler isn't included. You need to pre-compilation all message format."

Related error: https://github.com/nuxt-modules/i18n/issues/1956

**Comment by AnthonyRuelle** [comment] 2023-08-11 09:33
Why was this issue closed ?
Even on the latest version, the problem is still relevant and even locally ...

**Comment by jojomatik** [comment] 2023-09-01 21:02
I'm currently facing the same issue: I can see the translation keys shortly in the built version (https://nuxt.jojomatik.de/de/login).

After hydrationt hey are replaced by the correct texts. This also affects the link previews.

For me this issue is present since I updated nuxt and this package. See compare link: https://github.com/jojomatik/nuxt-3-base/compare/f162413a71b482dd4603ff07ed0fc587430a1ee5...7c9756a0fd43604191d7c8bd764789af4849fafd

**Comment by heshamabdallah** [comment] 2023-09-08 05:08
This is fixed by using `const { t } = useI18n()`  to get the translation keys `<span>{{ t('message') }}</span>`.. using `const { t: $t } = useI18n()` fails, it seems the global `$t` overrides the local one.

```vue
<template>
  <span>{{ t('message') }}</span>
 </template>
 
 <script setup>
 const { t } = useI18n()
 </script>
```

**Comment by jojomatik** [comment] 2023-09-11 13:40
For me this seems fixed after updating to 

```
    "@intlify/core-base": "9.3.0",
    "@intlify/shared": "9.3.0",
```

See https://github.com/jojomatik/nuxt-3-base/commit/82f03ff606060b24a368c72fa3928a44b5bd747f#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by BobbieGoede** [comment] 2024-02-16 11:17
Can someone confirm if this issue still present when using the latest release?

**Comment by MorevM** [comment] 2024-02-16 11:23
@BobbieGoede 

I can confirm that at least my part of the issue (see [comment with screenshot](https://github.com/nuxt-modules/i18n/issues/2111#issuecomment-1565458286)) is no longer occurring with `@nuxtjs/i18n@8.1.1`

**Comment by BobbieGoede** [comment] 2024-02-16 11:29
@MorevM 
Thanks for the very quick response! Happy to hear you're not experiencing the issue anymore, and in that case I'll close this issue. 

If anyone is still experiencing this issue with the latest version, please open a new issue with an up to date (minimal) reproduction!

**Closed as completed by BobbieGoede** 2024-02-16 11:29 UTC
Labels: v8, 🔨 p3-minor-bug, scope: ssr
