### ISSUE TITLE
The switchLocalePath method cannot get the incoming language address

### ISSUE THREAD

**Issue by rczdgbg** [nuxt-modules/i18n#2920] opened 2024-04-18 06:10 UTC
### Environment

Node Version: v20.11.0
Nuxt Version: 3.11.2
CLI Version: 3.11.2
Nitro Version: 2.9.6
Package Manager: pnpm@9.0.2

### Reproduction

https://stackblitz.com/edit/github-a5wazj-tp1y9r?file=pages%2Findex.vue

### Describe the bug

defaultLocale:'en'
expect:
   switchLocalePath("en") ---> /
   switchLocalePath("de") ---> /de
result:
   switchLocalePath("en") ---> /
   switchLocalePath("de") ---> /

**Comment by howbizarre** [comment] 2024-04-18 07:06
I'm having the same problem, but there's one more thing.

My switchLocale component is:

```
<script setup lang="ts">
import { LanguageIcon } from '@heroicons/vue/24/solid';

const { locale, locales } = useI18n();
const switchLocalePath = useSwitchLocalePath();
const otherAvailableLocales = computed(() => (locales.value).filter(i => i.code !== locale.value));
</script>

<template>
  <NuxtLink v-for="locale in otherAvailableLocales" :key="locale.code" :to="switchLocalePath(locale.code)" class="btn btn-default">
    <LanguageIcon class="btn--icon-left" /> {{ locale.name }}
  </NuxtLink>
</template>
```

but classes `router-link-active` and `router-link-exact-active` are added in the generated code

```
<a aria-current="page" href="/en" class="router-link-active router-link-exact-active btn btn-default">...</a>
```

Perhaps this is an effect due to the problem described above?

**Comment by anick-xs** [comment] 2024-04-18 07:12
I'm having the same problem too.

**Comment by rczdgbg** [comment] 2024-04-18 07:24
![image](https://github.com/nuxt-modules/i18n/assets/38928451/01830d7a-7968-4d9c-987b-196d517dad0a)

vue-router 4.3.1 There is a problem
4.3.0 no problem

**Comment by clairechang0609** [comment] 2024-04-18 07:47
same problem!

**Comment by BobbieGoede** [comment] 2024-04-18 08:22
@rczdgbg
You're right, a change in `vue-router@4.3.1` breaks route resolution, possibly https://github.com/vuejs/router/pull/2189. 

While we're trying to figure out why this is breaking I recommend overriding the version of `vue-router` to `4.3.0` in your package.json as a temporary workaround, you can do so by adding the following to your package.json:

```json
  "overrides" {
    "vue-router": "4.3.0"
  }
```

You may have to remove lockfiles before installing to make this work.

**Comment by BobbieGoede** [comment] 2024-04-18 10:14
The breaking change in `vue-router@4.3.1` has been reverted and released in `vue-router@4.3.2`, the workaround can be removed. Simply removing lockfiles and reinstalling dependencies should resolve this issue if you were experiencing it.

Closing this as resolved, if you're still experiencing issues let me know!

**Closed as completed by BobbieGoede** 2024-04-18 10:14 UTC
Labels: upstream, v8, workaround

**Comment by xushnudbek20** [comment] 2024-04-23 05:37
Still not working. My version: ^8.3.0

**Comment by BobbieGoede** [comment] 2024-04-23 06:41
> Still not working. My version: ^8.3.0

@xushnudbek20 
Have you read the comments in this issue? If you're still experiencing this issue can you open a new issue with a minimal reproduction?
