### ISSUE TITLE
Loading locale

### ISSUE THREAD

**Issue by Nojusle** [nuxt-modules/i18n#1282] opened 2021-09-11 14:56 UTC
### Is your feature request related to a problem? Please describe.

I have a use case where app user has to print an invoice in multiple different languages. ```$t(key: VueI18n.Path, locale: VueI18n.Locale, values?: VueI18n.Values)``` function accepts locale parameter, but if language is not yet loaded it does fallback to current user language, thus making locale parameter in this function totally useless.

Currently the only non hacky way to download required translation file is to use ```$i18n.setLocale()``` funcion, but this function changes app language and invokes other custom callbacks such as ```$i18n.onLanguageSwitched()```

### Describe the solution you'd like

the solution could be to expose ```$i18n.loadLocale(locale: string): Promise<void>``` function.

**Comment by rchl** [comment] 2021-09-12 18:27
Duplicate of #740

**Closed as completed by rchl** 2021-09-12 18:27 UTC
