### ISSUE TITLE
switchLocalePath(...) not working for 404 page

### ISSUE THREAD

**Issue by DamianGlowala** [nuxt-modules/i18n#1105] opened 2021-03-11 23:53 UTC
I can't get the switchLocalePath(...) function to work on custom 404 page (located in nuxt layouts/error.vue). It works great for other pages but I'm not sure if there's a way to make it work in this case. When I inspect the url my language switcher leads to, it remains the same but should be the other one the user can switch to... Is there anything I overlooked to get it working?

Any suggestions greatly appreciated!

**Comment by rchl** [comment] 2021-03-12 07:38
Duplicate of #976

**Closed as completed by rchl** 2021-03-12 07:38 UTC
