### ISSUE TITLE
Adding/enabling i18n results in "Cannot start nuxt: input.includes is not a function"

### ISSUE THREAD

**Issue by josvos** [nuxt-modules/i18n#2393] opened 2023-09-09 12:54 UTC
### Environment

- Operating System: Linux
- Node Version:     v18.16.1
- Nuxt Version:     3.7.1
- CLI Version:      3.8.1
- Nitro Version:    2.6.3
- Package Manager:  npm@9.5.1
- Builder:          -
- User Config:      css, devtools, experimental, modules, ssr, i18n, tailwindcss, app
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.4, @nuxtjs/tailwindcss@6.8.0
- Build Modules:    -

### Reproduction

**UPDATE**: I added a reproduction sample from Github in the next comment for this issue!

Adding @nuxtjs/i18n@next to a small Nuxt 3 project causes in the error `Cannot start nuxt: input.includes is not a function` when running `npm run dev`.  More details:

(1)
Existing Nuxt 3 project (versions 3.6.3 - 3.7.0  doesn't seem to matter) that works fine.

(2)
`npm install @nuxtjs/i18n@next` (installs 8.0.0-rc.4).
Add `'@nuxtjs/i18n'` to module list in nuxt.config.ts (defaultNuxtconfig).
Add to i18n section in nuxt.config.ts (defaultNuxtconfig):
```
  18n: {
    vueI18n: {
      runtimeOnly: false,
      fallbackLocale: 'en-US',
    },
  },
```

(3)
`npm run dev` results in ` ERROR  Cannot start nuxt:  input.includes is not a function`.
See bug description section for the stack trace.

(4)
When I comment out `'@nuxtjs/i18n'` in nuxt.config.ts, all is working fine again, so adding/enabling i18n definitely causes/triggers the problem.

### Describe the bug

`npm run dev` results in ` ERROR  Cannot start nuxt:  input.includes is not a function` with the following trace:
```
  at normalizeWindowsPath (node_modules/pathe/dist/shared/pathe.92c04245.mjs:2:24)
  at normalize (node_modules/pathe/dist/shared/pathe.92c04245.mjs:17:10)
  at resolvePath (node_modules/@nuxt/kit/dist/index.mjs:2340:10)
  at resolveVueI18nConfigInfo (node_modules/@nuxtjs/i18n/dist/module.mjs:244:43)
  at setup (node_modules/@nuxtjs/i18n/dist/module.mjs:1450:41)
  at async normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:2141:17)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2426:95)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:3533:7)
  at async NuxtDevServer._load (node_modules/nuxi/dist/chunks/dev.mjs:223:5)
  at async NuxtDevServer.load (node_modules/nuxi/dist/chunks/dev.mjs:174:7)
```

**Comment by josvos** [comment] 2023-09-09 15:47
UPDATE: it can be reproduced using this Github repo:
https://github.com/jahidanowar/nuxt3-i18n-tutorial.git

Clone this repo, `rm yarn.lock` (important!), and run `npm install`, which fails with the above mentioned error.

Clone thsi repo again, `rm yarn.lock` (important!), and now comment out the i18n module in nuxt.config.ts.  Then run `npm install` and that now suceeds, as i18n is not used!  Note that `npm run dev` of course doesn't work now, as the code is relying on the i18n module.

**Comment by BobbieGoede** [comment] 2023-09-10 08:37
Thank you for providing the reproduction, it looks like the issue is the `vueI18n` configuration. It should be set to a path to a file, not an object ([see docs here](https://v8.i18n.nuxtjs.org/options/vue-i18n)). I have changed your reproduction to demonstrate [here](https://stackblitz.com/edit/jahidanowar-nuxt3-i18n-tutorial-1dtqmo?file=nuxt.config.ts).

Let me know if you are still running into any issues after changing the configuration, I will be closing this issue for now.

**Closed as completed by BobbieGoede** 2023-09-10 08:37 UTC
Labels: v8, scope: configuration
