### ISSUE TITLE
concatenating with the + operator not work

### ISSUE THREAD

**Issue by julioglobal100** [nuxt-modules/i18n#2732] opened 2024-01-25 22:38 UTC
<img width="290" alt="image" src="https://github.com/nuxt-modules/i18n/assets/95880113/39c37397-0514-475d-bb6c-db04d100eae2">

I'm facing an issue with concatenating text using the + operator within the library. I have several files structured of this way
- Any option to allow line breaks?
- Any options to allow declaring variables inside the en.js file?

Thanks

**Comment by kazupon** [comment] 2024-01-26 01:56
Thank you for your feedback!

I do not know why it does not work with plus operator.
I think it works. 🤔 

I will advise you about i18n resource.
nuxt i18n (vue-i18n) supports definitions in programmable formats like `.ts` and `.js`.
If your project uses the localize service and has a separate localization and development workflow, it is recommended to define translation messages statically in those files.
This is because the general localize service supports integrating with a string of statically defined messages.
If you programmatically and dynamically define translation messages, they are difficult to integrate with the localize service.

When using `.ts` and `.js`, we assume a use case where the translation messages are fetched from a backend.
We would hope this advice will be of help to you.

Nuxt I18n issues are mainly for bug reports.
Since your issue is not a bug, please discuss it in github discussions or on the i18n channel of the Nuxt Discord.
So, I will close this issue.

Thank you!

**Closed as not planned** 2024-01-26 01:56 UTC
