### ISSUE TITLE
Pages that are created from `extendPages` or `pages:extend` hook in nuxt modules don't have locale routes

### ISSUE THREAD

**Issue by trandaison** [nuxt-modules/i18n#1894] opened 2023-02-28 14:47 UTC
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `pnpm@7.27.1`
- Builder:          `vite`
- User Config:      `experimental`, `plugins`, `css`, `build`, `modules`, `routeRules`, `runtimeConfig`, `i18n`, `auth`
- Runtime Modules:  `@pinia/nuxt@0.4.7`, `@nuxtjs/i18n@8.0.0-beta.10`, `./modules/auth`
- Build Modules:    `-`

### Reproduction

```ts
export default defineNuxtModule({
  setup(moduleOptions, nuxt) {
    nuxt.hook('pages:extend', (pages) => {
        pages.push({
          name: 'login',
          path: '/login',
          file: resolve(__dirname, './pages/login.vue'),
        });
    });
  },
});
```

### Describe the bug

Pages that are created from `extendPages` or `pages:extend` hook in nuxt modules don't have locale routes.

**Comment by kazupon** [comment] 2023-02-28 15:06
Thank you for your feedback!

Unfortunately, nuxt i18n module could not localized for your `pages:extend` hook.
We need to re-design for this cases.

**Comment by BobbieGoede** [comment] 2023-03-01 14:53
It looks like this should work as long as you load your module before `@nuxtjs/i18n`, I made a working example [here](https://stackblitz.com/edit/github-6vx1jm?file=nuxt.config.ts).

**Comment by trandaison** [comment] 2023-03-02 08:53
@BobbieGoede But what if the module depends on `@nuxtjs/i18n`? in that case, `@nuxtjs/i18n` need to be loaded first, isn't it?

**Comment by kazupon** [comment] 2023-03-02 09:28
@BobbieGoede 
Thank you your workaround!

Fundamentally, this issue should be ressolved with re-designed, but we would like to post your workaround in the nuxt i18n docs as well.
PR is welcome! :)

**Comment by BobbieGoede** [comment] 2023-03-02 09:56
@trandaison Can you give an example in which way the module would depend on `@nuxtjs/i18n`?

@kazupon I would be happy to open a PR to add it to the docs but I'm not sure where in the docs would be appropriate, I suppose the content/description would be similar to https://v8.i18n.nuxtjs.org/guide/extend-messages

**Comment by kazupon** [comment] 2023-03-02 14:15
@BobbieGoede 
I think that it should be noted on  the last of `Routing & Strategies` page.
https://v8.i18n.nuxtjs.org/guide/routing-strategies

And, that note section title would be wrriten `Routing for your extending page`.

**Comment by kazupon** [comment] 2023-03-02 14:17
Ah, I've just looked up your PR.
https://github.com/nuxt-modules/i18n/pull/1903

This's good!
Thanks!

**Comment by kazupon** [comment] 2023-03-03 14:32
Closed, so I merged #1903

**Closed as completed** 2023-03-03 14:32 UTC
Labels: feature request, v8, workaround

**Comment by trandaison** [comment] 2023-03-08 14:33
@BobbieGoede 
> @trandaison Can you give an example in which way the module would depend on @nuxtjs/i18n?

I'm writing an authentication module. In this module, I create a `$fetch` instance, there is a logic on `onResponseError` interceptor, if the request response 401 then redirect to login route.
I would like to localize the login route to redirect to correct locale login url.

I put the i18n module before my auth module, like this
```
  modules: ['@pinia/nuxt', '@nuxtjs/i18n', './modules/auth'],
```
But `useLocaleRoute` and `useLocalePath` are not working inside `onResponseError` interceptor too.

**Comment by BobbieGoede** [comment] 2023-03-08 16:43
@trandaison if you create a reproduction of your setup on stackblitz I could give it a closer look. 

Composables usually need to be called inside a certain context like the setup function of a component, I'm not sure if it is possible or recommended to use composables directly inside `onResponseError` of `$fetch`. You could wrap the `$fetch` usage inside another composable and passing `onResponseError` as an option inside of it see [this comment](https://github.com/nuxt/nuxt/issues/14736#issuecomment-1397364476) for reference.
