### ISSUE TITLE
How to add langs/locales list in nuxtjs-i18n configuration dynamically.

### ISSUE THREAD

**Issue by seetpalsingh** [nuxt-modules/i18n#2795] opened 2024-02-15 12:16 UTC
### Discussed in https://github.com/nuxt-modules/i18n/discussions/2794

<div type='discussions-op-text'>

<sup>Originally posted by **seetpalsingh** February 15, 2024</sup>
Hi Can someone plz guide me , how i can update/add list of locales in i18n configuration.

In nuxt.config.js i don't have list of langs. 
but on SSR I get list of locals/langs from strapi, that i want to add in i18 lang options list.

How i can do this.</div>

**Comment by BobbieGoede** [comment] 2024-02-15 12:20
It's currently not possible to change the configured locales at runtime, closing this as it is a duplicate of https://github.com/nuxt-modules/i18n/issues/2289.

**Closed as not planned by BobbieGoede** 2024-02-15 12:20 UTC
