### ISSUE TITLE
RuntimeConfig support for i18n-module

### ISSUE THREAD

**Issue by Sletheren** [nuxt-modules/i18n#1184] opened 2021-06-03 11:16 UTC
Hello,
My application is made so that we build one image and use it on different countries,
Meaning, we load the image that has been built, with a different set of environment variables.
In order to do that, one of our dependencies is `nuxt-i18n` but I don't see any option of passing the language settings (defaultLanguage/...etc) through runtime environment variables,

If I use `process.env.*` cuz it seems it gets parsed on buildtime,
Any solution for this?
Thank you.

**Comment by rchl** [comment] 2021-06-03 11:37
See https://github.com/nuxt-community/i18n-module/issues/1007

**Comment by Sletheren** [comment] 2021-06-03 15:58
Hi @rchl , i saw that issue and another related thread, so all in all, this is not possible to do using i18n and nuxt?
And what other solutions/directions u would suggest to solve this?

**Comment by andorfermichael** [comment] 2021-06-07 07:13
I have the same troubles like you @Sletheren Runtime config would be a great feature.

**Comment by rchl** [comment] 2021-06-07 20:43
Duplicate of #1007

I don't really see any alternative option currently besides building separately for each locale.

Maybe it would be possible to refactor the module to instead of generating routes up front would create more dynamic routes but it would be huge undertaking.

**Closed as completed by rchl** 2021-06-07 20:43 UTC
Labels: bug 🐛
