### ISSUE TITLE
$t does not retrieve messages from other languages

### ISSUE THREAD

**Issue by frbuceta** [nuxt-modules/i18n#842] opened 2020-08-12 12:02 UTC
### Version
nuxt-i18n: v6.13.8
nuxt: v2.14.1

#### [Mode](https://nuxtjs.org/api/configuration-mode): 
 - [X] universal
 - [ ] spa

### Nuxt-i18n configuration
```js
{
  /*
   ** I18N module configuration
   ** See https://i18n.nuxtjs.org/options-reference.html
   */
  i18n: {
    locales: [
      {
        code: 'en',
        file: 'en.js',
      },
      {
        code: 'es',
        file: 'es.js',
      },
      {
        code: 'gl',
        file: 'gl.js',
      },
    ],
    defaultLocale: 'en',
    lazy: true,
    langDir: 'locales/',
    detectBrowserLanguage: { useCookie: false },
  },
}
```

```js
computed: {
    availableLocaleOptions() {
      return this.$i18n.locales.map((o) => ({
        value: o.code,
        text:
          o.code === this.$i18n.locale
            ? this.$t(`locales.${o.code}`)
            : `${this.$t(`locales.${o.code}`)} (${this.$t(
                `locales.${o.code}`,
                o.code
              )})`,
        disabled: o.code === this.$i18n.locale,
      }))
    },
}
```

### Reproduction Link

I don't see it necessary

### Steps to reproduce
With the configuration code we can see that `$t(key, locale)` does not work

![Screenshot 2020-08-12 at 13 59 05](https://user-images.githubusercontent.com/13822438/90012637-0ed7ea80-dca4-11ea-9d13-2a91a08c8b1b.png)

### What is Expected?
The expected result is that you put the name of the language in your language in parentheses.

![Screenshot 2020-08-12 at 14 01 21](https://user-images.githubusercontent.com/13822438/90012781-55c5e000-dca4-11ea-8b5a-b2f13dea1fff.png)

### What is actually happening?
I don't know what's going on, but it's not working.

**Comment by rchl** [comment] 2020-08-12 12:50
When lazy loading only the current and fallback (if different than current) locales are loaded.

I think you're issue is a duplicate of https://github.com/nuxt-community/i18n-module/issues/740 .

**Comment by frbuceta** [comment] 2020-08-12 13:45
> When lazy loading only the current and fallback (if different than current) locales are loaded.
> 
> I think you're issue is a duplicate of #740 .

Ok, but I can't remove the lazy parameter because that is how the langDir parameter doesn't work.

I think this bug may have something to do with it https://github.com/nuxt-community/i18n-module/issues/412

**Comment by rchl** [comment] 2020-10-11 20:59
Duplicate of #740

**Closed as completed by rchl** 2020-10-11 20:59 UTC
Labels: bug 🐛
