### ISSUE TITLE
How to exclude a page from the generated routes

### ISSUE THREAD

**Issue by denisoed** [nuxt-modules/i18n#1263] opened 2021-08-13 05:55 UTC
Hi :)

I have configured two languages EN and RU.

![image](https://user-images.githubusercontent.com/17797700/129310500-167f349f-4432-4c2a-877d-030f19ed147f.png)

When I run the command `npm run generate`, in the folder dist, it creates routers with the prefix **/ru/...** as in the example below.

**/
/ru
/about
/ru/about
/contacts
/ru/contacts**

**Question** -> Can I ignore the creation of routes for certain pages when I run the `npm run generate` command?

For example, I would like to generate pages only for the "about" page. 

**/**
**/about**
**/ru/about** _<- include only this page_
**/contacts**

**Comment by rchl** [comment] 2021-08-13 06:56
Looks like you are asking the same question that is asked in #1262

**Comment by rchl** [comment] 2021-09-08 19:53
Duplicate of #1262

**Closed as completed by rchl** 2021-09-08 19:53 UTC
