### ISSUE TITLE
[NEXT] Lazy loading translations results in "Could not find nl locale" error

### ISSUE THREAD

**Issue by StefanVDWeide** [nuxt-modules/i18n#1511] opened 2022-09-10 18:03 UTC
### Version
@nuxtjs/i18n: 8.0.0-alpha.1
nuxt: 3.0.0-rc.9

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [x] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [ ] Applies to a site deployed to a server with a Node backend

### @nuxtjs/i18n configuration

```js
i18n: {
        baseUrl: 'https://studioterabyte.nl',
        locales: [
            {
                code: 'en',
                iso: 'en-US',
                file: 'en-US.js'
            },
            {
                code: 'nl',
                iso: 'nl-NL',
                file: 'nl-NL.js'
            }
        ],
        lazy: true,
        langDir: 'locales/',
        defaultLocale: 'nl',
        vueI18n: {
            legacy: false,
            fallbackLocale: 'nl',
            // seo: false,
        }
    }
```

### What is Expected?
For the correct locale to be loaded based on their respective `.js` file. 

### What is actually happening?
I've been migrating my Nuxt 2 site to Nuxt 3 and am currently working on i18n. My setup relies on 2 locale `.js` files (NL & EN) to load the correct text. I've followed the lazy loading documentation [here](https://v8.i18n.nuxtjs.org/guide/lazy-load-translations) but I keep getting the following errors:

```
[@nuxtjs/i18n] Could not find nl locale
[intlify] Not found 'navbar.links.services' key in 'nl' locale messages.
```

The component that uses the translation looks like (shortened for brevity):

```js
<template>
  <nuxt-link class="hover:underline" :to="localePath('/services')">
      {{ $t("navbar.links.services") }}
  </nuxt-link>
</template>

<script lang="ts" setup>
const switchLocalePath = useSwitchLocalePath();
const localePath = useLocalePath()

// Local state
const showMenu = ref<Boolean>(false);

// Methods
const toggleNavbar = (): void => { showMenu.value = !showMenu.value }

</script>
```

The locale file looks like:

```js
export default {
    ...
    "navbar": {
        "links": {
            "services": "Services",
            "cases": "Cases",
            "blog": "Blog",
            "over": "Over ons",
            "contact": "Contact"
        }
    },
    ...
}
```

Has this feature not been implemented yet in the Next branch or am I making a mistake somewhere?

Thanks in advance!

**Comment by steel97** [comment] 2022-09-11 07:10
Hi, it seems that this is still not supported.
See: [TO-DO.md](https://github.com/nuxt-community/i18n-module/blob/d1ee9d24c9ee19bbfdf91bd810126095f4965f55/TODO.md) **Lazy-load translations** section
Also see issues: #1462  #1448

**Comment by StefanVDWeide** [comment] 2022-09-11 10:38
The linked issues seem to suggest that JSON is currently supported, but unfortunately those also error out for me. When change the files to `JSON` files I get the following error:

```
Cannot read properties of undefined (reading 'message')
```

Is there anything else that needs to be enabled in order to support `JSON`? Or does the file need to have a particular format?

**Comment by warflash** [comment] 2022-09-15 16:49
@StefanVDWeide Did you find a solution to JSON lazy loading? My default locale loads perfectly fine with lazy: true but when I change the locale things don't update. Turning lazy: false fixes things not updating but that's not a very clean solution.

**Comment by StefanVDWeide** [comment] 2022-09-15 17:29
@warflash Unfortunately I did not. But it sounds like you are getting further than me. I'm simply getting a 500 error when I tried to load the JSON messages, lazy or not lazy. Could you share what your `nuxt.config.ts` file looks like? And maybe a sample of your JSON locale file? For some reason I get:

```zsh
 ERROR  Cannot read properties of undefined (reading 'message')   
```

with my JSON file looking like:

```JSON
{
    "home": {
        "hero": {
            "h1": "made to measure",
            "h2": "Studio Terabyte is a fullstack web development studio who finds and builds solutions that fit your project"
        },
   ....
}
```
and my `nuxt.config.ts` looking like:

```ts
i18n: {
        baseUrl: 'https://studioterabyte.nl',
        locales: [
            {
                code: 'en',
                iso: 'en-US',
                file: 'en-US.json'
            },
            {
                code: 'nl',
                iso: 'nl-NL',
                file: 'nl-NL.json'
            }
        ],
        lazy: true,
        langDir: 'locales/',
        defaultLocale: 'nl',
        vueI18n: {
            legacy: false,
            fallbackLocale: 'nl',
            // seo: false,
        }
    }
```

**Comment by warflash** [comment] 2022-09-15 19:23
Ah that's unlucky, really trying to get lazy loading to work :/
My nuxt config looks like this: 
```js
i18n: {
    langDir: "locales/",
    locales: [
      {
        iso: "en-US",
        code: "en",
        file: "en.json",
      },
    ...
    ],
    detectBrowserLanguage: false,
    strategy: "no_prefix",
    lazy: false,
    defaultLocale: "en",
    vueI18n: {
      legacy: false,
      fallbackLocale: "en",
      locale: "en",
    },
  },
```

**Comment by StefanVDWeide** [comment] 2022-09-15 22:19
@warflash Okay I figured out my issue. For some reason having a "@" symbol in the JSON file breaks the whole pluging. I'm going to open a separate issue with more details. Thanks for thinking along!

**Comment by warflash** [comment] 2022-09-16 00:38
Gotcha, so does removing the @ also make lazy loading work for you?

**Comment by kazupon** [comment] 2022-09-20 16:47
duplicate in https://github.com/nuxt-community/i18n-module/issues/1519
I've fixed in `@intlify/unplugin-vue-i18n` latest version.
You can check in v8.0.0-alpha.2 or edge version.

Thanks!

**Closed as completed** 2022-09-20 16:47 UTC
Labels: bug 🐛, v8

**Comment by Nobi322** [comment] 2022-10-05 06:57
> duplicate in #1519 I've fixed in `@intlify/unplugin-vue-i18n` latest version. You can check in v8.0.0-alpha.2 or edge version.
> 
> Thanks!

@kazupon Was .js translations with Promises also fixed? Because on edge I still get  "[@nuxtjs/i18n] Could not find de locale".

**Comment by junogueira** [comment] 2023-01-13 20:37
@warflash Did you manage to get `lazy` working?

Having the same issue you reported. Everything works great with `lazy: false`.

**Comment by prazian** [comment] 2024-02-12 09:04
I faced the same issue with json. Changed it to TS, still lazy loading doesn't work.

```
nuxt: "^3.10.1",
vue: "^3.4.15",
@nuxtjs/i18n: "^8.1.0"
```

nuxt.config.ts:
```
...
  i18n: {
    defaultLocale: "en",
    langDir: "lang",
    lazy: true, //changing to false fixes this
    baseUrl: process.env.BASE_URL || "https://something",
    locales: [
      {
        code: "en",
        iso: "en-US",
        file: "en.ts",
      },
      ...
    ],
  },
...
```

When `lazy` is set to `true`, I get a warning message like this:
`[intlify] Not found 'blah-blah' key in 'fr' locale messages.`

When I set it to false, it works.
Tested with json and typescript, and it's the same.

**Comment by BobbieGoede** [comment] 2024-02-12 10:33
@prazian 
Please open a new issue with a minimal reproduction, this issue has been closed for a long time and the cause of your issue is unlikely to be the same.
