### ISSUE TITLE
Having an "@" symbol in the locale JSON file breaks the plugin and results in a 500 error

### ISSUE THREAD

**Issue by StefanVDWeide** [nuxt-modules/i18n#1519] opened 2022-09-15 22:35 UTC
### Version
@nuxtjs/i18n: 8.0.0-alpha.1
nuxt: 3.0.0-rc.9

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [x] Applies to a site deployed to a static server (site generated with `nuxt generate`)

### @nuxtjs/i18n configuration

```js
i18n: {
        baseUrl: 'https://studioterabyte.nl',
        locales: [
            {
                code: 'en',
                iso: 'en-US',
                file: 'en-US.js'
            },
            {
                code: 'nl',
                iso: 'nl-NL',
                file: 'nl-NL.js'
            }
        ],
        lazy: true,
        langDir: 'locales/',
        defaultLocale: 'nl',
        vueI18n: {
            legacy: false,
            fallbackLocale: 'nl',
        }
    }
```

### What is Expected?
For the correct locale to be loaded based on their respective `.json` file. 

### What is actually happening?
When trying to load my locales via `JSON` files I kept encountering an error messages indicating that the message property could not be read:

```zsh
 ERROR  Cannot read properties of undefined (reading 'message')    
```

After some investigating I found that having an "@" symbol anywhere in the file will cause the plugin to return the error message above and render the 500 error page. I've recreated the error here:

https://stackblitz.com/edit/nuxt-starter-xohyax?file=package.json

Thanks!

**Comment by kazupon** [comment] 2022-09-16 18:14
Thank you for your reporting!

This issue is caused by `@intlify/bundle-utils`.

related issue: https://github.com/intlify/bundle-tools/issues/164
related PR: 
https://github.com/intlify/bundle-tools/pull/173

So, When the about PR is merged, this issue will be resolved

**Closed as completed** 2022-09-20 15:39 UTC
Labels: bug 🐛, v8
