### ISSUE TITLE
With strategy `prefix`, unprefixed routes are accessible

### ISSUE THREAD

**Issue by huang-julien** [nuxt-modules/i18n#2131] opened 2023-06-02 13:46 UTC
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.20.0
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-vdw3ue?file=pages%2Ftest.vue,pages%2Findex.vue,package.json

### Describe the bug

When using `prefix` strategy, we can see that the unprefixed route is still registered within the router.
When going to the unregistered route, we can still access to it without being redirected.

![image](https://github.com/nuxt-modules/i18n/assets/63512348/22422bb8-43cb-4117-b97a-e03e0cccab48)

**Comment by kazupon** [comment] 2023-06-06 05:51
Thank you for your reporting!
I could not reproduce this issue.
I got the below error:

```sh
 ERROR  Error while requiring module /path/to/2132/modules/routing/index.vue: SyntaxError: Unexpected token '<'                                  14:44:50


 ERROR  Cannot start nuxt:  Unexpected token '<'                                                                                                                                             14:44:50

  <template>
  ^

  SyntaxError: Unexpected token '<'
  at internalCompileFunction (node:internal/vm:73:18)
  at wrapSafe (node:internal/modules/cjs/loader:1176:20)
  at Module._compile (node:internal/modules/cjs/loader:1218:27)
  at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
  at Module.load (node:internal/modules/cjs/loader:1117:32)
  at Module._load (node:internal/modules/cjs/loader:958:12)
  at Module.require (node:internal/modules/cjs/loader:1141:19)
  at require (node:internal/modules/cjs/helpers:110:18)
  at jiti (node_modules/jiti/dist/jiti.js:1:243592)
  at requireModule (node_modules/@nuxt/kit/dist/index.mjs:274:26)

```

I seem your reproduction is updated after your opened this issue.

Could you give us your reproduction again please?  🙏

**Comment by huang-julien** [comment] 2023-06-06 07:19
oops it should be updated now 😅 . To reproduce it, you can simply make a hard reload on `/test`. The full path will be shown

**Comment by kazupon** [comment] 2023-06-07 03:43
Thank you for your updating!
I could confirm this issue.

We will try to fix.

**Comment by huang-julien** [comment] 2023-06-07 07:29
I guess that a workaround is to add a middleware that redirect to the localeRoute ifthe user is not on a localizedRoute
`````ts
useNuxtApp().$getBaseRouteName(to.name) === to.name
````

**Comment by Blemming** [comment] 2023-06-14 12:54
> I guess that a workaround is to add a middleware that redirect to the localeRoute ifthe user is not on a localizedRoute
> 
> ```ts
> useNuxtApp().$getBaseRouteName(to.name) === to.name
> ````

To extend on this, using getBaseRouteName. This is what works for me:
```ts
export default defineNuxtRouteMiddleware((to) => {
  const context = useNuxtApp()
  if (context.$getRouteBaseName(to) === to.name)
    return navigateTo(context.$localePath(to), { replace: true })
})
```

**Comment by nonlinearcom** [comment] 2023-07-07 19:41
I guess this is fixed in v8.0.0-beta.13 ? 
I'm getting the redirect even without the middleware workaround 🤔

**Comment by huang-julien** [comment] 2023-07-08 00:42
A lot of bux fixes came with beta 13. I don't have time to check my issues now but if this is fixed, expect this to be closed in the next week

**Comment by Red-Asuka** [comment] 2023-07-10 02:01
I have upgraded to beta 13, but the problem still exists. Unprefixed routes are still registered in the router. However, when accessing "/", language detection and redirection will occur. Unfortunately, the system does not remember the language of the user's last visit. This is my i18n configuration.

```ts
const i18n: NuxtI18nOptions = {
  lazy: true,
  langDir: 'lang/',
  defaultLocale: 'en',
  strategy: 'prefix',
  detectBrowserLanguage: {
    alwaysRedirect: true,
    fallbackLocale: 'en',
    redirectOn: 'root',
    useCookie: true,
    cookieCrossOrigin: false,
    cookieDomain: process.env.NODE_ENV === 'production' ? process.env.COOKIES_DOMAIN : null,
    cookieKey: 'i18n_redirected',
    cookieSecure: false,
  },
  locales: [
    {
      code: 'en',
      name: 'English',
      iso: 'en',
      files: getFiles('en'),
    },
    {
      code: 'zh',
      name: '中文',
      iso: 'zh',
      files: getFiles('zh'),
    },
    {
      code: 'ja',
      name: '日本語',
      iso: 'ja',
      files: getFiles('ja'),
    },
  ],
}
```

<img width="1278" alt="image" src="https://github.com/nuxt-modules/i18n/assets/38158783/4975565b-17a8-40c1-9d25-7d897cf227d8">

**Comment by huang-julien** [comment] 2023-08-25 14:33
@kazupon 
Are we supposed to keep the untranslated routes even if they are not accessible anymore ?
![image](https://github.com/nuxt-modules/i18n/assets/63512348/ed468298-48dd-4bdd-8e92-6818b7e87497)

**Comment by kazupon** [comment] 2023-08-28 06:40
@huang-julien 
Yeah, I think we don't need to support i18n  routing for Catch all / 404 Not found Route, because that's no point.

**Comment by luca-smartpricing** [comment] 2023-09-13 13:52
Some news with this bug?
It creates a lot of hassle during generation because it creates useless pages and with plugins like [nuxt-simple-sitemap](https://github.com/harlan-zw/nuxt-simple-sitemap) that index inaccessible pages

**Comment by rudolfbyker** [comment] 2023-10-25 08:11
I would expect the unprefixed routes to be removed when using the `prefix` strategy, rather than having each one redirect to the prefixed version of it.

**Comment by kazupon** [comment] 2023-12-04 14:56
close with #2538

**Closed as completed by kazupon** 2023-12-04 14:56 UTC
Labels: v8, 🔨 p3-minor-bug, scope: routing, PR Welcome
