### ISSUE TITLE
SEO trailingSlash is being appended twice on 404 URLs

### ISSUE THREAD

**Issue by divine** [nuxt-modules/i18n#2532] opened 2023-11-03 23:10 UTC
### Reproduction

https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-fpyfzn?file=nuxt.config.ts

### Describe the bug

trailingSlash is being appended at the end of URL on 404 pages:

Go to reproduction URL, type any random address that doesn't exist like `/en/t/` and you'll get URL appended twice:

```
<link rel="alternate" href="https://google.com/en/t//" hreflang="en" data-hid="7fcee50">
--
  | <link rel="alternate" href="https://google.com/en/t//" hreflang="en-US" data-hid="1b5d3fd">
  | <link rel="alternate" href="https://google.com/nl/t//" hreflang="nl" data-hid="cbabfd6">
  | <link rel="alternate" href="https://google.com/nl/t//" hreflang="nl-NL" data-hid="4afbd03">
  | <link rel="alternate" href="https://google.com/ja/t//" hreflang="ja" data-hid="396afb4">
  | <link rel="alternate" href="https://google.com/ja/t//" hreflang="ja-JA" data-hid="fbe5b58">
  | <link rel="alternate" href="https://google.com/en/t//" hreflang="x-default" data-hid="6527e7a">
  | <link rel="canonical" href="https://google.com/en/t//" data-hid="5cca6f5">
  | <meta property="og:url" content="https://google.com/en/t//">
  | <meta property="og:locale" content="en_US">
  | <meta property="og:locale:alternate" content="nl_NL">
  | <meta property="og:locale:alternate" content="ja_JA">
```

Thanks!

**Comment by BobbieGoede** [comment] 2024-02-05 15:39
Closing this as I'm unable to reproduce this using the latest release, looks like it has been fixed already 😄

**Closed as completed by BobbieGoede** 2024-02-05 15:39 UTC
Labels: v8, 🔨 p3-minor-bug, scope: seo
