### ISSUE TITLE
Nuxt `context.route` not updated (in time) when using `switchLocalePath()` to change locale.

### ISSUE THREAD

**Issue by lagset** [nuxt-modules/i18n#1199] opened 2021-06-15 11:52 UTC
### Version

vue: 2.6.12
nuxt: 2.15.2
vue-i18n: 8.24.3
nuxt-i18n: 6.20.4

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [x] target: static
 - [x] ssr: true

### Nuxt-i18n configuration

The configuration of the project I first encountered this issue, probably not relevant:
```
i18n_____*/
  i18n: {
    strategy: "prefix_except_default",
    locales: [
      {
        code: "de",
        file: "de-DE.js",
        name: "Deutsch",
      },
      {
        code: "en",
        file: "en-US.js",
        name: "English",
      },
    ],
    defaultLocale: "de",
    lazy: true,
    langDir: "lang/",
    vueI18nLoader: false,
}
```

### Reproduction Link

https://codesandbox.io/s/vue-i18nvalidate-0mp02

If you use the sandbox with vue-i18n **v8.24.2** and load the page and click on "Switch to en" you will get the route `{name: "index___en",...` output from `validate` via `console.log` . Which is the expected behaivour.

Try changing the vue-i18n version to **v8.24.3** wait for build and reload the page, then click on "Switch to en" you will get the route `{name:"index___de",...` output from `validate` via `console.log` .

### Steps to reproduce

See Reproduction Link.

Install and setup a nuxt project with a version of nuxt-i18n which requires vue-i18n@^v8.24.3.
Setup a few pages, the nuxt-i18n languages files and a button which triggers nuxt-i18n `switchLocalePath`.

Then build/run dev mode, access the page and click on the button to trigger `switchLocalePath`. Log the contents of nuxt context on route change via nuxt `validate()`, `asyncData()` or `fetch()`.

### What is Expected?

When navigating to a new route, the new route is present in nuxt `context.route`, e.g. so on `validate()` execution the new route and its params can be accessed to match it with vuex store data or something else.

### What is actually happening?

When navigating to a new route, the old route is still present in nuxt `context.route`, e.g. on `validate()` execution.

### Further information

I already opened an [issue at vue-i18n](https://github.com/kazupon/vue-i18n/issues/1230)
But I am not sure,  if it is their part to solve this issue.

I found this [stackoverflow post](https://stackoverflow.com/questions/67240236/nuxt-context-route-not-updated-in-asyncdata), whose author seems to struggle with the same problem.:

**Comment by rchl** [comment] 2021-06-15 19:48
Since you've verified that switching `vue-i18n` version makes a difference, that seems like a pretty strong indication that the issue is there. Let's discuss there first.

**Comment by rchl** [comment] 2021-06-21 06:38
Looks like fixed in `vue-i18n` (https://github.com/kazupon/vue-i18n/issues/1230).

**Closed as completed by rchl** 2021-06-21 06:38 UTC
Labels: bug 🐛
