### ISSUE TITLE
localePath/localeRoute on nested route return redirected path

### ISSUE THREAD

**Issue by mrleblanc101** [nuxt-modules/i18n#1248] opened 2021-07-28 15:20 UTC
### Version
nuxt-i18n: 6.21.1
nuxt: 2.15.3

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [x] universal
 - [ ] spa

### Reproduction Link

Coming later

### Steps to reproduce
I'm trying to link to `/directory`, so i use `<nuxt-link class="menu-link" :to="localePath({ name: 'directory' })">` (see router bellow).
Instead of printing `/directory` as the path, it nuxt-i18n resolve the redirect and print `/directory/professionnals` which break the `.router-link-active` and `.router-link-exact-active` behavior. 
My menu item doesn't get the class when I go to the sub-routes.
This seems like an issue with `localePath/localeRoute` as if I do not use them, the path is printed correctly (doesn't resolve the redirect).
The issue is that my link will not work in all language `<nuxt-link class="menu-link" :to="{ name: 'directory___en' }">`
```
{
    path: '/en/directory',
    component: Directory,
    children: [
        {
            path: '',
            name: 'directory___en',
            redirect: { name: 'directory-professionals___en' },
        },
        {
            path: 'professionnals',
            name: 'directory-professionals___en',
            component: DirectoryProfessionnals,
        },
        {
            path: 'organizations',
            name: 'directory-organizations___en',
            component: DirectoryOrganizations,
        },
        {
            path: 'tools',
            name: 'directory-tools___en',
            component: DirectoryTools,
        },
    ],
},
```

### What is Expected?
localePath/localeRoute should return the first matched path and not the redirect path. Then my menu item path would be `/directory` and would receive `.router-link-active` class when I navigate to a sub-route.

### What is actually happening?
localePath/localeRoute return the redirect path. Then my menu item path is be `/directory/professionnals` so it does not receive `.router-link-active` class when I navigate to a sub-route.

**Comment by mrleblanc101** [comment] 2021-07-28 15:33
Here is what happen:
![2021-07-28 11 32 41](https://user-images.githubusercontent.com/17392251/127351553-1fc7bebe-cd60-44cb-b9fa-3268fbd13259.gif)

**Comment by mrleblanc101** [comment] 2021-07-28 15:34
Here is what happen if I remove the localePath (but my link only work in one language now):
![2021-07-28 11 34 20](https://user-images.githubusercontent.com/17392251/127351823-dcbc86cf-7a56-4cbb-bd57-8475723eb24c.gif)

**Comment by mrleblanc101** [comment] 2021-07-28 15:44
My current solution if anyone face the sam problem:
```html
<!-- <nuxt-link class="menu-link" :to="localePath({ name: 'directory' })"> --> // this will print "/directory/professionnals"
<nuxt-link class="menu-link" :to="{ name: `directory___${$i18n.locale}` }"> // this will print "/directory"
```

**Comment by rchl** [comment] 2021-07-28 18:01
Interesting case...

We always resolve the provided input with VueRouter and it returns the redirected route.

Not resolving the input would have very big implications everywhere so I don't think that would be an option...

(BTW. Not related to the problem but `localePath({ name: 'directory' })` is equivalent to the shorter `localePath('directory')`.)

**Comment by mrleblanc101** [comment] 2021-07-28 18:09
@rchl 
I'm not sure how nuxt-i18n resolve the route using Vue-router as sending the route object directly to `nuxt-link/router-link` or using `$router.resolve({ name: 'directory___en' })` return the correct URL (not the redirected one).

This might be a breaking change, but I still think it's a bug. It break some native Vue-router behavior. 
I think nuxt-i18n should mimic the router native behavior when translating links.
Because the link in our side menu is the redirected one instead of the parent one, it does not get `.router-link-active` class because vue think it's a sibling route instead of a parent route.

Also I think sending a string instead of an object to `localePath`, it expect the argument to be a path which we don't like.
We prefer using name everywhere in our application instead of path. Also, this mimic the `router-link` native behavior.

**Comment by rchl** [comment] 2021-07-28 20:14
`localePath` is not supposed to be an equivalent to `$route.resolve` since it's specified to return a plain string so it needs to resolve the input.

`localeRoute` and `localeLocation` could possibly return something closer to the input.

> using `$router.resolve({ name: 'directory___en' })` return the correct URL (not the redirected one).

Not sure about that because that's basically what this module does.
If you can create a reproduction then I will have a closer look.

**Comment by mrleblanc101** [comment] 2021-07-28 20:23
Maybe I wasn't clear, but from what I understand:

`localePath` is the equivalent of `$route.resolve(...).href` because it return the path of the resolved route object.
It should return the path of the parent route, not the redirected child route just like how vue-router work IMO.
`localeRoute` is the equivalent of a plain `$route.resolve(...)` because it return the route object with a translated name attribute

I'll try to post a repro tonight

**Comment by rchl** [comment] 2021-07-28 20:25
`localeRoute` basically resolves the route and returns `resolvedRoute.route.fullPath`.

**Comment by mrleblanc101** [comment] 2021-07-28 20:36
Vue-router seem to directly return `resolvedRoute.href` which will follow the redirect on click. It wont resolve the redirected URL at compilation. https://github.com/vuejs/vue-router/blob/73459565c4c64bfe9b41341875a84c87bc8b931c/src/components/link.js#L48

I'll get back to you with a repro. 
But to me, it seem logical that adding a redirect in the router should not rewrite URL already in the app.

**Comment by mrleblanc101** [comment] 2021-08-04 03:14
@rchl 
Here is the sandox link: https://codesandbox.io/s/angry-haibt-d2t97?file=/router.js
Sorry for the delay.

I've created a menu with some random page.
I created 2 link to the page "Directory".
One with localePath, one without localPath.
Watch what happen to the active style when you change tabs from "professionnals" to "organizations" or "tools".

This only happen in the case of sub-route with redirect on the base route.
This is because localePath follow the redirect so it break the relationship between the page parent page and the menu-element.

![2021-08-03 23 17 54](https://user-images.githubusercontent.com/17392251/128116780-27019e3e-cf24-4f61-abff-d3902545acf9.gif)

**Comment by mrleblanc101** [comment] 2021-08-04 03:22
I know v7 was just released today, but v7.1 would be the right time to make this breaking change and fix this behavior as very few people started using v7.

**Comment by divine** [comment] 2021-08-04 07:43
> I know v7 was just released today, but v7.1 would be the right time to make this breaking change and fix this behavior as very few people started using v7.

Hello,

There is no reason that this behavior should be changed. You have created this issue only 7 days ago and asking for a breaking change that can't be done with the one click. It needs time and consideration.

Thanks!

**Comment by rchl** [comment] 2021-08-04 08:21
Breaking change would require major version change or be an opt-in. It's not an option to make a breaking change and disguise it as minor because the new version was just released.

But it has to be investigated what effect would that have, starting with checking tests.

I believe the `route.href` is set regardless if route exists or not so that would be a major difference compared to the current behavior.

**Comment by mrleblanc101** [comment] 2021-08-04 13:41
@divine There is many reason why this behavior should be changed as I've shown many time in the thread.
Whether you decide to do it or not is a different story.

I thought a breaking change was fine in a minor (not a patch) if it does not change the API but I must be mistaken.
I don't think it's a big change that would require a lot of work/refactor if you decide to mirror Vue-router behavior.
If you decide this should be fixed in a v8, this should be done quickly as people are already moving processing v7 changes but you do as you think is right.

I'll leave you two more time to analyse the impact.

**Comment by rchl** [comment] 2021-08-04 21:26
There seems to be a simple and safe fix for this that will only affect this specific case (redirects).

The `href` property is created by `VueRouter` with a code like this:

```js
function createHref (base, fullPath, mode) {
  var path = mode === 'hash' ? '#' + fullPath : fullPath
  return base ? cleanPath(base + '/' + path) : path
}

const fullPath = route.redirectedFrom || route.fullPath
const base = this.history.base
const href = createHref(base, fullPath, this.mode)
```

We don't really want to use the `href` directly since it would introduce two issues:
 - in `hash` mode, the `#` would get included in the resolved path which would result in duplicate hash when using the resolved value within `<nuxt-link>`
 - the router base would get included in the resolved path which would be wrong since vue router doesn't expect it to be explicitly passed when navigating

So the solution is to return `route.redirectedFrom || route.fullPath` instead of `route.fullPath` and skip the extra logic that `href` includes. #1253 should fix it.

**Closed as completed** 2021-08-04 22:25 UTC
Labels: bug 🐛

**Comment by mrleblanc101** [comment] 2021-08-04 22:29
Thanks you, that's fantastic. So fast ! 

So is this still a breaking change ? If so when can we expect the next release ? Will you create a version with only this fix or are you waiting until more change are merged ?

**Comment by rchl** [comment] 2021-08-05 08:19
I'd consider it a bug fix since it's so localized and matches vue-router closer.
Will release it right away.

**Comment by mrleblanc101** [comment] 2021-08-06 01:03
I confirm that this fix my issue. Thanks again !
I've upgraded from 6.28.0 to 7.0.1 without problem.
Just needed to remember abou the change from nuxt-i18n to @nuxtjs/i18n
