### ISSUE TITLE
Enabling i18n causes inline styles/TailwindCSS to break in production

### ISSUE THREAD

**Issue by renegadevi** [nuxt-modules/i18n#2177] opened 2023-06-24 00:16 UTC
### Environment

```
------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.0
- Nitro Version:    2.5.1
- Package Manager:  pnpm@8.6.3
- Builder:          vite
- User Config:      experimental, modules, i18n
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @nuxtjs/i18n@8.0.0-beta.12
- Build Modules:    -
------------------------------
```

### Reproduction

[https://stackblitz.com/edit/github-9ukebr-ssoaxr?file=nuxt.config.ts](https://stackblitz.com/edit/github-9ukebr-ssoaxr?file=nuxt.config.ts)

### Describe the bug

When adding/enabling the i18n module, it causes TailwindCSS to break in production when making a build.

### Additional context

By adding this to the `nuxt.config.ts`, it will work again.
```
experimental: {
    inlineSSRStyles: false,
},

```
Tried downgrading versions but same result. Tried both Node 16 on stackblitz and 18 locally, same result.

### Logs

```shell
```

**Comment by kazupon** [comment] 2023-06-24 01:57
Thank you for your reporting!

Unfortunately, We could not reproduce this issue on stackbliz.
I could not saw tailwindcss breaking.
Could you give us more your reporting info please?  🙏 
(By the way, I don't know much about tailwindcss. I would like to know how it is broken.)

**Comment by renegadevi** [comment] 2023-06-24 11:51
![Skärmavbild 2023-06-24 kl  13 45 19](https://github.com/nuxt-modules/i18n/assets/10997469/c27f7ffb-1a55-4097-bb05-5437fb1f19c0)
See screenshot. Without adding experimental, it shows no styling. If you enable it,  issue is gone.

**Not working:**
https://stackblitz.com/edit/github-9ukebr-ssoaxr?file=nuxt.config.ts

**Working:**
https://stackblitz.com/edit/github-9ukebr-n26mat?file=nuxt.config.ts

**Comment by erikuit** [comment] 2023-06-27 08:00
Not using Tailwind here, but we have the same issue using Nuxt 3.6.0 and 3.6.1. None of the global styles included via the css property in nuxt.config are loaded. Nuxt version 3.5 works without any problems.

**Comment by dargmuesli** [comment] 2023-07-01 18:33
See https://github.com/nuxt/nuxt/pull/21864. Would you try Nuxt's current edge release? Otherwise you could wait for Nuxt v3.6.2: https://github.com/nuxt/nuxt/pull/21813

**Comment by dargmuesli** [comment] 2023-07-01 18:39
See the updated reproduction: https://stackblitz.com/edit/github-9ukebr-jn38u1?file=nuxt.config.ts,package.json

**Comment by kazupon** [comment] 2023-07-03 07:56
This issue has been resolved with nuxt.
@dargmuesli reproduction shows that it is working with the nuxt edge channel. (Thanks!)

So, close

**Closed as not planned** 2023-07-03 07:56 UTC
Labels: upstream, v8, workaround
