### ISSUE TITLE
Messages in the console when using global translations instead of local ones.

### ISSUE THREAD

**Issue by xeqtr-zhg** [nuxt-modules/i18n#2812] opened 2024-02-20 08:02 UTC
### Environment

nuxt 3

### Reproduction

Messages in the console when using global translations instead of local ones.

### Describe the bug

Hello, I ran into a problem, there are a lot of messages in the console that the local translation was not found and the global file was used (this is predictable behavior, that's how I intended it), these messages are very annoying, how can they be disabled?

Not found 'breadcrumbs.home' key in 'en' locale messages.
Fall back to translate 'breadcrumbs.home' with root locale.

**Comment by BobbieGoede** [comment] 2024-02-21 16:24
These warnings are logged by `vue-i18n`, I think this [issue comment](https://github.com/nuxt-modules/i18n/issues/2136#issuecomment-1579769152) will resolve your issue. Closing this as this is not caused by this module.

**Closed as not planned by BobbieGoede** 2024-02-21 16:24 UTC
Labels: pending triage
