### ISSUE TITLE
dynamic i18n doesn't work in server middleware

### ISSUE THREAD

**Issue by AriesAlex** [nuxt-modules/i18n#2220] opened 2023-07-10 12:29 UTC
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.13-28149586.8d65ac4
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-nxfsvv
npm run buildAndStart

### Describe the bug

In theory #2199 should have fixed it but it doesn't

when using i18n in dedicated middleware and using it in endpoint it's just returning translation key and prints in logs:
[intlify] The message format compilation is not supported in this build. Because message compiler isn't included. You need to pre-compilation all message format. So translate function return 'test'.

**Comment by kazupon** [comment] 2023-07-11 02:24
Hi!
Thank you for your reproduction!

The issue is that the vue-i18n message-compiler for the server side is not made to use the jit compilation.
I’ll try to fix later.

**Comment by kazupon** [comment] 2023-07-11 02:24
BTW, From your issue's use case, I could get the inspiration for the server side i18n.
The nuxt i18n module will be a priority for the v8 RC release.
When that version will be released,  maybe I will try to implement as a nitro plugin and integrated into the nuxt i18n module.

The core of vue-i18n is designed in framework agnostic, so logically it can integrate for other frameworks.
Thanks for this issue of yours! /cc @danielroe @pi0

**Closed as completed** 2023-07-11 07:16 UTC
Labels: v8, 🔨 p3-minor-bug, scope: nitro
