### ISSUE TITLE
Strategy `prefix_and_default` seems to be broken again

### ISSUE THREAD

**Issue by szwenni** [nuxt-modules/i18n#2259] opened 2023-07-24 12:54 UTC
### Environment

- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@3.2.3
- Builder:          vite
- User Config:      devtools, rootDir, buildDir, runtimeConfig, colorMode, app, eslint, modules, extendedSitemap, tailwindcss, i18n, build
- Runtime Modules:  @nuxtjs/eslint-module@4.1.0, @nuxtjs/color-mode@3.3.0, @nuxtjs/tailwindcss@6.8.0, @nuxtjs/robots@3.0.0, @pinia/nuxt@0.4.11, @nuxtjs/i18n@8.0.0-beta.13
- Build Modules:    -

### Reproduction

* setup project with strategy `prefix_and_default` and create a toplevel parameterized page like `pages/[name].vue`
* add at least one language
* add some nuxtlinks to the parameterized pages
* routing will not happen as the i18n guard resolved the navigation back to the same route again, independently where you are right now (I still did not figure out why)
* routing will be canceled

### Describe the bug

* no navigation is possible with nuxt links

### Additional context

I tried my best to pinpoint the code location where this is happening but debugging is quite hard
The i18n nuxt module prints out that the resolved location is always the same as the current and therefore cancels the routing

The problem does not occur with strategy `no_prefix` and also on beta-11 the problem did not exist

**Comment by kazupon** [comment] 2023-07-25 10:36
Thank you for your reporting!
But, We need your minimul reproduction, because we can reproduce your issue.
Could you give us it with stackbliz or github repo please? 🙏

**Comment by szwenni** [comment] 2023-07-25 11:01
Hi
https://github.com/szwenni/i18n-router-bug-2259

To reproduce:
* Install dependencies `npm install`
* Run the project with `npm run dev`, you can click the links but nothing happens, from the debug logs of i18n you can see that it always resolves back to `/`

Like said I'm not really sure by looking at the code where the issue is in the i18n module. I'm sure you can pinpoint it quite fast why this happens.

It must be some change introduced between beta-9 and beta-12.

BR,
Sven

**Comment by szwenni** [comment] 2023-07-25 11:17
I don't even know why it even enters this if block https://github.com/nuxt-modules/i18n/blob/937686d0f50305be898761191b3aed62ad6c902f/src/runtime/utils.ts#L305 because of the condition `strategy !== 'prefix_and_default'` https://github.com/nuxt-modules/i18n/blob/937686d0f50305be898761191b3aed62ad6c902f/src/runtime/utils.ts#L309

I have the strategy set to `prefix_and_default`. It should not enter this block but it actually prints the debug message `detectRedirect: calculate routePath -> / /A`.
https://github.com/nuxt-modules/i18n/blob/937686d0f50305be898761191b3aed62ad6c902f/src/runtime/utils.ts#L315

**Comment by szwenni** [comment] 2023-07-25 11:44
I think the issue can be (most probably) closed
I built the module locally and included it in the project as local module. It started to work there. That is most probably also the reason why I was not able to pinpoint the issue. It is already fixed (I think). It would be cool if you can verify that.

**Comment by szwenni** [comment] 2023-07-25 11:51
https://github.com/nuxt-modules/i18n/blob/39d2bf74c7beaf6d47141075eecd730ea9cba332/src/runtime/utils.ts#L304C71-L304C71

This was the line why it jumped into the if block, so yeah I assume it is fixed

**Comment by kazupon** [comment] 2023-07-26 02:51
Yes, this issue has already been resolved. The bugfix will be released in v8.0.0-beta.14. If you want to use the fixed version, you can use the edge channel version.

```json
"@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge"
```

**Comment by kazupon** [comment] 2023-07-26 02:53
this issue is same as #2244  (duplication issue)
so close.

thanks!

**Closed as not planned by kazupon** 2023-07-26 02:53 UTC
Labels: v8, scope: routing
