### ISSUE TITLE
Import the i18n plugin for composition api

### ISSUE THREAD

**Issue by bissolli** [nuxt-modules/i18n#986] opened 2020-12-07 06:25 UTC
Is there a way to import the translator method to use with composition API? I actually don't want to get it from the root or from nuxt context, I would like to do something like:

```javascript
import { useI18n } form "@nuxtjs/i18n"

export default {
   setup() {
      const { t } = useI18n();

      return {
          t
      }
   }
}
```

The reason is that I would like to keep things the more clear and decoupled possible! And I am also mocking the nuxtContext for my tests are quite annoying! Would be much simpler mocking the plugin i18n itself.

**Comment by rchl** [comment] 2020-12-07 08:13
The composition API in general has to be implemented.
I've created a general feature request now at https://github.com/nuxt-community/i18n-module/issues/987

**Comment by rchl** [comment] 2021-02-07 20:51
Duplicate of #987

**Closed as completed by rchl** 2021-02-07 20:51 UTC
Labels: feature request

**Comment by giuliano-oliveira** [comment] 2021-05-25 14:28
@rchl still a problem specific for i18n, sure a lot of composables are supported, but i18n is still not
