### ISSUE TITLE
[Bug]: Adding i18n module to Nuxt breaks typing for all components in Nuxt app

### ISSUE THREAD

**Issue by martinszeltins** [nuxt-modules/i18n#2839] opened 2024-03-14 17:19 UTC
### Environment

Stackblitz

````
------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    -
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      extends
- Runtime Modules:  -
- Build Modules:    -
------------------------------
````

### Reproduction

https://stackblitz.com/github/martinszeltins/found-nuxt-components-issue?file=app.vue

### Describe the bug

When I add this module to my modules array in nuxt.config.ts then I lose all typings for my components _(for both local and 3rd party components)._ It shows that components have type of `unknown`. Before I add this module, everything works.

**nuxt.config.ts** 👇️
```diff
modules: [
+  '@nuxtjs/i18n', // This breaks all auto-import component typings (components not recognized anymore)
   '@vueuse/nuxt',
   'nuxt-primevue'
],
```

If I remove it from my modules array then everything works again.

**Screenshot before adding the module (everything works):** 👍️  👇️

![image](https://github.com/nuxt/nuxt/assets/34019878/510078e3-3e45-42d0-ab79-e678815d2325)

**Screenshot after adding the module (type unknown):** ❌  👇️

![image](https://github.com/nuxt/nuxt/assets/34019878/8cdb9168-5bdc-4642-a7a4-44829c3c5e44)

**Comment by BobbieGoede** [comment] 2024-03-14 22:46
Hmm, I'm pretty sure this is caused by the types provided by `primevue`. We ran into a similar issue some time ago, I'll see if I can open a PR to fix it on their end.

**Comment by BobbieGoede** [comment] 2024-03-15 11:44
As you have noticed, I opened a PR (https://github.com/primefaces/primevue/pull/5419) on their repo to resolve your issue, since this isn't caused by this module I'll close this issue. 

I recommend opening an issue on their repo and referencing the PR (and this issue), as their [PR template](https://github.com/primefaces/primevue/blob/master/.github/PULL_REQUEST_TEMPLATE.md) seems to require it, this may not be necessary anymore since they've added the PR to the next milestone.

**Closed as completed by BobbieGoede** 2024-03-15 11:44 UTC
Labels: v8, scope: types

**Comment by martinszeltins** [comment] 2024-03-15 13:17
> As you have noticed, I opened a PR ([primefaces/primevue#5419](https://github.com/primefaces/primevue/pull/5419)) on their repo to resolve your issue, since this isn't caused by this module I'll close this issue.
> 
> I recommend opening an issue on their repo and referencing the PR (and this issue), as their [PR template](https://github.com/primefaces/primevue/blob/master/.github/PULL_REQUEST_TEMPLATE.md?rgh-link-date=2024-03-15T11%3A44%3A19Z) seems to require it, this may not be necessary anymore since they've added the PR to the next milestone.

Thank you!
