### ISSUE TITLE
 ERROR  Cannot start nuxt:  Cannot find module '@intlify/vue-i18n-bridge/lib/index.mjs'            

### ISSUE THREAD

**Issue by SamHoque** [nuxt-modules/i18n#1654] opened 2022-11-18 09:37 UTC
### Version
@nuxtjs/i18n: ^8.0.0-beta.4
nuxt: ^3.0.0-rc.12

### Steps to reproduce
1. Add `'@nuxtjs/i18n'` to `nuxt.config.js`
2. Run `npm run dev`

### What is Expected?
Nuxt to run properly

### What is actually happening?
Throwing an error

```
 ERROR  Cannot start nuxt:  Cannot find module '@intlify/vue-i18n-bridge/lib/index.mjs'                                                                                                                                       16:33:12
Require stack:
- C:\Workspace\website\frontend\index.js

  Require stack:
  - index.js
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at Function._resolve [as resolve] (node_modules\jiti\dist\jiti.js:1:243257)
  at resolveModule (/C:/Workspace/website/frontend/node_modules/@nuxtjs/i18n/node_modules/@nuxt/kit/dist/index.mjs:260:29)
  at setupAlias (/C:/Workspace/website/frontend/node_modules/@nuxtjs/i18n/dist/module.mjs:48:52)
  at setup (/C:/Workspace/website/frontend/node_modules/@nuxtjs/i18n/dist/module.mjs:641:11)
  at async Object.normalizedModule (/C:/Workspace/website/frontend/node_modules/@nuxtjs/i18n/node_modules/@nuxt/kit/dist/index.mjs:167:5)
  at async installModule (/C:/Workspace/website/frontend/node_modules/@nuxt/kit/dist/index.mjs:456:3)
  at async initNuxt (/C:/Workspace/website/frontend/node_modules/nuxt/dist/index.mjs:1686:7)
  at async load (/C:/Workspace/website/frontend/node_modules/nuxi/dist/chunks/dev.mjs:6778:9)


```

**Comment by andreidmour** [comment] 2022-11-18 14:05
I confirm this bug, don't have any solution yet.

**Comment by madebyfabian** [comment] 2022-11-18 23:33
Can confirm, on nuxt@3.0.0 and nuxt-i18n@beta4. Installing the `@intlify/vue-i18n-bridge` package just throws up more dependency errors

**Comment by MusicOnline** [comment] 2022-11-19 04:21
Duplicate of #1640

**Comment by kazupon** [comment] 2022-11-19 06:07
I think this issue is resolved edge version.
See details #1640 comments

Thanks!

**Closed as completed** 2022-11-19 06:07 UTC
Labels: bug 🐛, v8
