### ISSUE TITLE
Adding an email to a locale crashes app

### ISSUE THREAD

**Issue by this-oliver** [nuxt-modules/i18n#2609] opened 2023-12-10 12:57 UTC
### Environment

- Operating System: Darwin
- Node Version:     v18.18.0
- Nuxt Version:     -
- CLI Version:      3.10.0
- Nitro Version:    -
- Package Manager:  pnpm@8.9.2
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

repoduction link: https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-qmxeki?file=locales%2Fen.json

add an email to a message will crash the application.

```html
<script>
// setup code
const en = {
message: "Interested in joining our dog club? Don't hesitate to email us at woof@example.com!"
};
</script>

<template>
<p>{{ $t("message") }}</p>
</template>
```

but if you format the message so that you can plug in the email, then i18n works as normal.

```html
<script>
// setup code
const en = {
message: "Interested in joining our dog club? Don't hesitate to email us at {email}!"
};
</script>

<template>
<p>{{ $t("message", {email: 'woof@example.com'}) }}</p>
</template>
```

### Describe the bug

The message fails to render an the following error message is logged: 

> "[plugin:unplugin-vue-i18n] Invalid linked format (error code: 10) in /home/projects/bobbiegoede-nuxt-i18n-starter-qmxeki/locales/en.json
>
> target message: Interested in joining our dog club? Don't hesitate to email us at woof@example.com!"

### Additional context

I suspect that this occurs because of the email because once you format the email part of the message, then the problem no longer appears.

Also, the error message in nuxt is not that helpful:
<img width="717" alt="Screenshot 2023-12-10 at 13 56 42" src="https://github.com/nuxt-modules/i18n/assets/32515201/7c50ab8f-1be7-4f31-a820-20699818eb5e">

### Logs

```shell
SyntaxError: 10
    NuxtJS 127
        as
        d
        ne
        be
        R
        f
        v
        g
        p
        pE
        tT
        nT
        Ab
        Fm
        ee
        $
        ee
        default
        a
        P$
        default
        a
        setup
        Ws
        qe
        ue
        run
        update
        N
        W
        d
        v
        f
        d
        qe
        ue
        run
        update
        N
        W
        d
        qe
        ue
        run
        update
        N
        W
        d
        qe
        ue
        run
        update
        N
        W
        d
        qe
        ue
        run
        update
        N
        W
        d
        gk
        d
        qe
        ue
        run
        update
        N
        W
        d
        qe
        ue
        run
        update
        N
        W
        d
        v
        h
        d
        v
        f
        d
        qe
        ue
        run
        update
        N
        W
        d
        v
        f
        d
        qe
        ue
        run
        update
        N
        W
        d
        v
        f
        d
        qe
        ue
        run
        update
        N
        W
        d
        v
        h
        d
        v
        f
        d
        qe
        ue
        run
        update
        N
        W
        d
        v
        h
        d
entry.3914b2c7.js:1:13754
    NuxtJS 172
        ak
        mo
        Ws
        qe
        ue
        run
        update
        N
        W
        d
        v
        f
        d
        qe
        ue
        run
        update
        N
        W
        d
        qe
        ue
        run
        update
        N
        W
        d
        qe
        ue
        run
        update
        N
        W
        d
        qe
        ue
        run
        update
        N
        W
        d
        gk
        d
        qe
        ue
        run
        update
        N
        W
        d
        qe
        ue
        run
        update
        N
        W
        d
        v
        h
        d
        v
        f
        d
        qe
        ue
        run
        update
        N
        W
        d
        v
        f
        d
        qe
        ue
        run
        update
        N
        W
        d
        v
        f
        d
        qe
        ue
        run
        update
        N
        W
        d
        v
        h
        d
        v
        f
        d
        qe
        ue
        run
        update
        N
        W
        d
        v
        h
        d
        v
        f
        d
        v
        f
        d
        qe
        ue
        run
        update
        N
        W
        d
        qe
        ue
        run
        update
        N
        W
        d
        qe
        ue
        run
        update
        N
        registerDep
    (Async: promise callback)
        registerDep
        W
        d
        qe
        ue
        run
        update
        N
        W
        d
        gk
        d
        qe
        ue
        run
        update
        N
        W
        d
        qe
        ue
        run
        update
        N
        W
        d
        gk
        d
        qe
        ue
        run
        update
        N
        W
        d
        c
        mount
        mount
        fg
        <anonymous>
```

**Comment by BobbieGoede** [comment] 2023-12-10 13:16
Closing this as this is not a bug but caused by `@` being a special character in Vue I18n v9, see [this comment](https://github.com/nuxt-modules/i18n/issues/2271) or the Vue I18n docs [here](https://vue-i18n.intlify.dev/guide/essentials/syntax#special-characters).

I agree the browser console error could be better, it looks like the `unplugin-vue-i18n` error is relatively informative. Maybe it could suggest that one of the special characters has been used incorrectly.

**Closed as completed by BobbieGoede** 2023-12-10 13:16 UTC
Labels: v8

**Comment by this-oliver** [comment] 2023-12-10 13:21
(_just a heads up_) the application doesn't crash in development but does once it is built. the logs I uploaded are from the production deployment.
