### ISSUE TITLE
Use .env variables on defineI18nConfig

### ISSUE THREAD

**Issue by 50l3r** [nuxt-modules/i18n#2548] opened 2023-11-09 19:27 UTC
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.17.1
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.1
- Package Manager:  npm@9.6.7
- Builder:          -
- User Config:      app, routeRules, modules, css, runtimeConfig, components, typescript, postcss, nitro, srcDir, hooks, devtools
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.1, @nuxtjs/i18n@8.0.0-rc.5, @nuxt/image@1.0.0, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.0, nuxt-ssr-cache@1.5.2
- Build Modules:    -
------------------------------

### Reproduction

```ts
import type { LocaleMessage } from '@intlify/core-base'
import type { VueMessageType } from '@nuxtjs/i18n/dist/runtime/composables'

export default defineI18nConfig(async () => ({
    legacy: false,
    locale: 'es',
    messages: await loadLocale()
}))

type Strings = Record<string, LocaleMessage<VueMessageType>>

const loadLocale = (): Promise<Strings> => {
    return new Promise((resolve, reject) => {
        fetch(`${process.env.NUXT_PUBLIC_API_URL}/cms/strings`, {
            method: 'GET',
            headers: {
                'Content-Type': 'application/json',
                'Accept': 'application/json'
            }
        })
            .then(async (res) => {
                const data = await res.json()
                resolve(data)
            })
            .catch((error) => {
                reject(error)
            })
    })
}
```

### Describe the bug

I need to use environment variables inside `defineI18nConfig` but i recieve undefined in some cases:

`[Vue Router warn]: No match found for location with path "/undefined/cms/strings"`

I receive the correct string at the start but after a while it stops working.

https://github.com/nuxt-modules/i18n/assets/5095592/9d3d5964-8fc6-495b-a348-ed68a4139dad

There seems to be a point where I do get access to `process.env.NUXT_PUBLIC_API_URL` but it stops working after a while.

I cannot access `useRuntimeConfig` either because I am not in the nuxt context.

**Comment by kazupon** [comment] 2023-11-11 16:17
Hmm, it seems that it is not accessible in the `defineI18nConfig` called in the plugin. 🤔 

@danielroe 
The `defineI18nConfig` is loaded by a plugin defined by nuxt i18n via `defineNuxtPlugin`. As far as I am aware, it is then accessible via public values (`useRuntimeConfig`) defined in environment variables by nuxt. Why can't I access it on the plugin side?

**Comment by BobbieGoede** [comment] 2023-11-12 11:44
@kazupon @danielroe 
After trying to debug this issue, I found that `useRuntimeConfig` does not work (seems to work client side?) if the dynamic imports for the i18n configs are imported from within a function in the generated `i18n.options.mjs` file (this function gets [called from plugin](https://github.com/nuxt-modules/i18n/blob/main/src/runtime/plugins/i18n.ts#L63)). 

This does work if the imports happen directly inside the plugin, see https://github.com/BobbieGoede/i18n-module/pull/18 (still need to clean it up a bit, hence PR on my fork). Maybe it is preferable to move that logic out of the generated file anyway so that the types get checked. 

I don't know why this does work and the other approach does not 😅.. Maybe there is an easy way to debug this that I'm unaware of 🤔.

**Comment by BobbieGoede** [comment] 2023-11-17 15:30
I'm closing this as it should be possible to use `useRuntimeConfig` on the edge release channel since #2252. Let me know if you're running into any issues, will reopen if that is the case!

**Closed as completed by BobbieGoede** 2023-11-17 15:30 UTC
Labels: upstream, v8

**Comment by mctweb** [comment] 2023-11-27 13:15
I'm still having issues with this - 
[nuxt] [request error] [unhandled] [500] [nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at `https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables`.

This is using '"@nuxtjs/i18n": "8.0.0-rc.5",'

**Comment by LorenzoRottigni** [comment] 2025-02-18 14:51
Hello there,
I found out something similar today after upgrading both nuxt and nuxt/i18n to the latest version... i'm no longer able to call useRuntimeConfig() from within the defineI18nLocale callback (throwing an error about a composable called outside the nuxt setup context). 
I can't neither use process.env.NUXT_PUBLIC_ENDPOINT since defineI18nLocale is called both on server and client side and it isn't available on client side... I can't see a way to provide a dynamic endpoint in there...
I might try a workaround like:

```
if (import.meta.browser) {
  const { public } = useRuntimeConfig()
  public.endpoint
} else {
  const endpoint = process.env.NUXT_PUBLIC_ENDPOINT
}
```

But it doesn't look that good D:

@BobbieGoede may you reopen this issue? :)

**Comment by BobbieGoede** [comment] 2025-02-18 14:55
@LorenzoRottigni we're tracking this regression here https://github.com/nuxt-modules/i18n/issues/3359 and I have a possible fix ready https://github.com/nuxt-modules/i18n/pull/3360

**Comment by LorenzoRottigni** [comment] 2025-02-18 14:55
nice! my workaround works anyway!

<img width="541" alt="Image" src="https://github.com/user-attachments/assets/6405b4b3-6d69-47ee-8692-8d54e14ae880" />
