### ISSUE TITLE
After updating nuxt and i18n versions, i18n strictMessage doesn't work.

### ISSUE THREAD

**Issue by yongho0605** [nuxt-modules/i18n#2947] opened 2024-05-13 06:42 UTC
### Environment

- Operating System: Darwin
- Node Version:     v20.9.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.1.0
- Builder:          -
- User Config:      experimental, runtimeConfig, app, build, modules, sitemap, i18n, css
- Runtime Modules:  @formkit/nuxt@1.5.9, @nuxtjs/tailwindcss@6.11.4, @nuxt/image@1.4.0, nuxt-lodash@2.5.3, @nuxtjs/sitemap@5.1.2, @nuxtjs/i18n@8.3.1
- Build Modules:    -

### Reproduction
https://stackblitz.com/edit/github-vzm2gj?file=package.json,locales%2Fko.json,locales%2Fen.json,nuxt.config.ts,app.vue

### Describe the bug

I updated my production application libraries after a long time and got an error.
The error I reported is that if you remove the <br />tags in the <i18n> scope of each single file component, the application works fine.

##Conclusion
- When I reproduced the error, I got the following error message
![스크린샷 2024-05-13 오후 3 28 49](https://github.com/nuxt-modules/i18n/assets/127718221/8c34e26c-79f5-49f3-9558-e221a945f6dd)

![스크린샷 2024-05-13 오후 3 29 07](https://github.com/nuxt-modules/i18n/assets/127718221/568f94ab-eb50-40c8-b112-59c9fdc0a848)

## Before version
- Nuxt Version:  3.6.1
- nuxtI18n Version: 8.0.0-beta.13

## Current nuxt config setting
```javascript
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  experimental: {
    inlineSSRStyles: false
  },
  runtimeConfig: {
    public: {
      apiUrl: process.env.NUXT_PUBLIC_API_URL || 'https://admin.application.io/api',
      mediaUrl: process.env.NUXT_PUBLIC_MEDIA_URL || '/media'
    }
  },
  app: {
    rootId: 'application',
    buildAssetsDir: '/_static/',
    head: {
      title: 'application',
      meta: [
        { charset: 'utf-8' },
        { name: 'viewport', content: 'width=device-width, initial-scale=1' },
    }
  },
  build: {
    transpile: ['@heroicons/vue', 'gsap']
  },
  modules: ['@formkit/nuxt', '@nuxtjs/tailwindcss', '@nuxt/image', 'nuxt-lodash', '@nuxtjs/sitemap', '@nuxtjs/i18n'],
  sitemap: {
    url: 'https://www.application.io', 
    xsl: false,
    exclude: ['/inquiries/**']
  },
  i18n: {
    langDir: './locales',
    baseUrl: 'https://www.application.io',
    lazy: true,
    detectBrowserLanguage: {
      fallbackLocale: 'ko',
      cookieSecure: true
    },
    locales: [
      { code: 'ko', iso: 'ko-KR', file: 'ko.json', name: 'KOR' },
      { code: 'en', iso: 'en-US', file: 'en.json', name: 'ENG' }
    ],
    defaultLocale: 'ko',
    strategy: 'no_prefix',
    compilation: { strictMessage: false }
  },
  css: ['~/assets/main.css']
})

```

## Updated package.json
```json
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare",
    "lint": "eslint . --fix --ext .js,.vue",
    "prettier": "prettier . --write",
    "prepare": "husky install",
    "set-husky": "husky add .husky/pre-commit \"npm run lint-staged\"",
    "lint-staged": "lint-staged"
  },
  "devDependencies": {
    "@nuxt/image": "^1.4.0",
    "@nuxtjs/eslint-config-typescript": "^12.1.0",
    "@nuxtjs/i18n": "^8.3.1",
    "@nuxtjs/sitemap": "^5.1.2",
    "@nuxtjs/tailwindcss": "^6.1.3",
    "@tailwindcss/typography": "^0.5.8",
    "eslint": "^8.57.0",
    "eslint-config-prettier": "^9.1.0",
    "husky": "^8.0.3",
    "lint-staged": "^15.2.2",
    "nuxt": "^3.11.2",
    "nuxt-lodash": "^2.5.0",
    "prettier": "^3.2.5",
    "prettier-plugin-tailwindcss": "^0.5.11",
    "sass": "^1.64.2",
    "tailwindcss": "^3.3.2",
    "typescript": "^5.1.3"
  },
  "dependencies": {
    "@formkit/nuxt": "^1.2.2",
    "@formkit/pro": "^0.117.5",
    "@formkit/themes": "^1.2.2",
    "@formkit/validation": "^1.2.2",
    "@headlessui/vue": "^1.7.4",
    "@heroicons/vue": "^2.0.13",
    "gsap": "^3.11.3",
    "tailwind-scrollbar-hide": "^1.1.7",
    "vue3-carousel": "^0.2.8",
    "vue3-marquee": "^3.1.2"
  },
  "lint-staged": {
    "./**/*.{js,ts,vue}": [
      "eslint --fix",
      "prettier --write"
    ]
  }
}

```

### Additional context

I don't know where the crash is happening.

**Comment by kazupon** [comment] 2024-06-24 05:40
Thank you for your reporting!

Unfortunately, We could not reproduce your reproduction. 😞 
Could you give us your minimal new reproduction? 🙏

**Comment by BobbieGoede** [comment] 2024-07-31 10:57
This issue is caused by devtools processing the html in the translation strings (see https://github.com/nuxt/devtools/issues/572).

You can add the following to `nuxt.config.ts` to prevent this from happening:
```ts
devtools: {
    enabled: true,
    componentInspector: false,
},
```

Closing this as there's not much we can do about it from our side.

**Closed as not planned by BobbieGoede** 2024-07-31 10:57 UTC
Labels: v8, need reproduction

**Comment by mrc-bsllt** [comment] 2025-04-26 14:28
Same problem in v.9.5.3
I tried to add `componentInspector: false` and also tried to disabled devtools, but not works.

**Comment by BobbieGoede** [comment] 2025-04-26 14:47
@mrc-bsllt 
Could you open a new issue with a minimal reproduction? 🙏

**Comment by mrc-bsllt** [comment] 2025-04-26 15:03
@BobbieGoede https://github.com/nuxt-modules/i18n/issues/3580
